version: "3"
services:
  client:
    tty: true
    image: client
    ports:
      - "3000:3000"
  java:
    tty: true
    image: java
    ports:
      - "8080:8080"
  mongo:
    ports:
      - "27017:27017"
    tty: true
    image: mongo
    volumes:
      - ./data:/data/db