services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: strongpassword
      MONGO_INITDB_DATABASE: localdb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_container
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpassword
    ports:
      - "8081:8080"
    command: [ "start-dev" ]
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:latest
    container_name: keycloak_postgres
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpassword
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      LOCAL_MONGODB_URI: "mongodb://admin:strongpassword@mongodb:27017/localdb"
      KEYCLOAK_URL: "http://keycloak:8081"
    depends_on:
      - mongodb
      - keycloak

volumes:
  mongo-data:
    driver: local
  keycloak-db-data:
    driver: local
