version: '3.8'

services:
  fullstack-app:
    image: generalraven1/fullstack-app:latest
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: /run/secrets/MONGODB_URI
    secrets:
      - MONGODB_URI
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure