version: "3.8"
services:
  client:
    build:
      context: client
    restart: always
    stdin_open: true
    networks:
      - react-java
    depends_on:
        - java
    ports:
      - "3000:3000"
  java:
    build:
      context: java-server
    restart: always
    volumes:
      - ./:/app
    depends_on:
        - mongo
    networks:
      - java-mongo
      - react-java
    expose:
      - 3000
  mongo:
    restart: always
    networks:
      - java-mongo
    expose:
      - 27017
    image: mongo
    volumes:
      - ./data:/data/db
networks:
  react-java:
  java-mongo: