version: "3.8"
services:
  client:
    build:
      context: client
    restart: always
    stdin_open: true
    networks:
      - react-gradle-java
    depends_on:
        - gradle-java
    ports:
      - "3000:3000"
  gradle-java:
    build:
      context: gradle-java-server
    restart: always
    networks:
      - react-gradle-java
    ports:
      - "8080:8080"
networks:
  react-gradle-java: