version: "3.8"
services:
  client:
    build:
      context: client
    restart: always
    stdin_open: true
    networks:
      - react-maven-java
    depends_on:
        - maven-java
    ports:
      - "3000:3000"
  maven-java:
    build:
      context: maven-java-server
    restart: always
    volumes:
      - ./:/app
    depends_on:
        - mongo
    networks:
      - maven-java-mongo
      - react-maven-java
    ports:
      - "8080:8080"
  mongo:
    restart: always
    networks:
      - maven-java-mongo
    expose:
      - 27017
    image: mongo
    volumes:
      - ./data:/data/db
networks:
  react-maven-java:
  maven-java-mongo: