version: "3"
services:
  genesys:
    tty: true
    image: genesys
    ports:
      - "8080:8080"
  mongo:
    ports:
      - "27017:27017"
    tty: true
    image: mongo
    command: -v ./data:/data/db