name = "genesys"
pages_build_output_dir = "build"
compatibility_date = "2024-05-29"
compatibility_flags = [ "nodejs_compat" ]

[env.production]
compatibility_date = "2024-05-29"
[[env.production.d1_databases]]
binding = "GENESYS"
database_name = "genesys"
database_id = "d6502d51-8c36-4d1f-bbce-80c1f938c776"

[[env.preview.d1_databases]]
binding = "GENESYS"
database_name = "genesys-test"
database_id = "e8b60884-bec5-4666-9ba5-feba365ef205"