/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CharacterResponse,
  Player,
  ServerResponse
} from '.././model';





/**
 * @summary Get all player characters
 */
export const getPlayer1 = (
    player: Player[], options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CharacterResponse[] | ServerResponse>> => {
    
    
    return axios.default.get(
      `/api/characters/players`,options
    );
  }


export const getGetPlayer1QueryKey = (player?: Player[],) => {
    return [`/api/characters/players`, player] as const;
    }

    
export const getGetPlayer1QueryOptions = <TData = Awaited<ReturnType<typeof getPlayer1>>, TError = AxiosError<unknown>>(player: Player[], options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlayer1>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPlayer1QueryKey(player);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlayer1>>> = ({ signal }) => getPlayer1(player, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPlayer1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPlayer1QueryResult = NonNullable<Awaited<ReturnType<typeof getPlayer1>>>
export type GetPlayer1QueryError = AxiosError<unknown>


export function useGetPlayer1<TData = Awaited<ReturnType<typeof getPlayer1>>, TError = AxiosError<unknown>>(
 player: Player[], options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlayer1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlayer1>>,
          TError,
          Awaited<ReturnType<typeof getPlayer1>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlayer1<TData = Awaited<ReturnType<typeof getPlayer1>>, TError = AxiosError<unknown>>(
 player: Player[], options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlayer1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlayer1>>,
          TError,
          Awaited<ReturnType<typeof getPlayer1>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlayer1<TData = Awaited<ReturnType<typeof getPlayer1>>, TError = AxiosError<unknown>>(
 player: Player[], options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlayer1>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all player characters
 */

export function useGetPlayer1<TData = Awaited<ReturnType<typeof getPlayer1>>, TError = AxiosError<unknown>>(
 player: Player[], options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlayer1>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPlayer1QueryOptions(player,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



