/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Archetype,
  Career,
  Characteristic,
  Player,
  PlayerResponse,
  PlayerSkill,
  Talent
} from '.././model';





/**
 * @summary Retrieve all players in a campaign
 */
export const getAllPlayers = (
    name: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PlayerResponse[]>> => {
    
    
    return axios.default.get(
      `/api/campaigns/${name}/players/`,options
    );
  }


export const getGetAllPlayersQueryKey = (name?: string,) => {
    return [`/api/campaigns/${name}/players/`] as const;
    }

    
export const getGetAllPlayersQueryOptions = <TData = Awaited<ReturnType<typeof getAllPlayers>>, TError = AxiosError<unknown>>(name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPlayers>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllPlayersQueryKey(name);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllPlayers>>> = ({ signal }) => getAllPlayers(name, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(name), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllPlayers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllPlayersQueryResult = NonNullable<Awaited<ReturnType<typeof getAllPlayers>>>
export type GetAllPlayersQueryError = AxiosError<unknown>


export function useGetAllPlayers<TData = Awaited<ReturnType<typeof getAllPlayers>>, TError = AxiosError<unknown>>(
 name: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPlayers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllPlayers>>,
          TError,
          Awaited<ReturnType<typeof getAllPlayers>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllPlayers<TData = Awaited<ReturnType<typeof getAllPlayers>>, TError = AxiosError<unknown>>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPlayers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllPlayers>>,
          TError,
          Awaited<ReturnType<typeof getAllPlayers>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllPlayers<TData = Awaited<ReturnType<typeof getAllPlayers>>, TError = AxiosError<unknown>>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPlayers>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieve all players in a campaign
 */

export function useGetAllPlayers<TData = Awaited<ReturnType<typeof getAllPlayers>>, TError = AxiosError<unknown>>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPlayers>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllPlayersQueryOptions(name,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const createPlayer = (
    name: string,
    playerName: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PlayerResponse>> => {
    
    
    return axios.default.post(
      `/api/campaigns/${name}/players/${playerName}`,undefined,options
    );
  }



export const getCreatePlayerMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPlayer>>, TError,{name: string;playerName: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createPlayer>>, TError,{name: string;playerName: string}, TContext> => {

const mutationKey = ['createPlayer'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPlayer>>, {name: string;playerName: string}> = (props) => {
          const {name,playerName} = props ?? {};

          return  createPlayer(name,playerName,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePlayerMutationResult = NonNullable<Awaited<ReturnType<typeof createPlayer>>>
    
    export type CreatePlayerMutationError = AxiosError<unknown>

    export const useCreatePlayer = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPlayer>>, TError,{name: string;playerName: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPlayer>>,
        TError,
        {name: string;playerName: string},
        TContext
      > => {

      const mutationOptions = getCreatePlayerMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const updatePlayerArchetype = (
    id: string,
    archetype: Archetype, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PlayerResponse>> => {
    
    
    return axios.default.patch(
      `/api/players/api/players/creation/${id}/archetypes/`,
      archetype,options
    );
  }



export const getUpdatePlayerArchetypeMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlayerArchetype>>, TError,{id: string;data: Archetype}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updatePlayerArchetype>>, TError,{id: string;data: Archetype}, TContext> => {

const mutationKey = ['updatePlayerArchetype'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePlayerArchetype>>, {id: string;data: Archetype}> = (props) => {
          const {id,data} = props ?? {};

          return  updatePlayerArchetype(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePlayerArchetypeMutationResult = NonNullable<Awaited<ReturnType<typeof updatePlayerArchetype>>>
    export type UpdatePlayerArchetypeMutationBody = Archetype
    export type UpdatePlayerArchetypeMutationError = AxiosError<unknown>

    export const useUpdatePlayerArchetype = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlayerArchetype>>, TError,{id: string;data: Archetype}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePlayerArchetype>>,
        TError,
        {id: string;data: Archetype},
        TContext
      > => {

      const mutationOptions = getUpdatePlayerArchetypeMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const updatePlayerCharacteristic = (
    id: string,
    characteristic: Characteristic, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PlayerResponse>> => {
    
    
    return axios.default.patch(
      `/api/players/api/players/creation/${id}/characteristics/`,
      characteristic,options
    );
  }



export const getUpdatePlayerCharacteristicMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlayerCharacteristic>>, TError,{id: string;data: Characteristic}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updatePlayerCharacteristic>>, TError,{id: string;data: Characteristic}, TContext> => {

const mutationKey = ['updatePlayerCharacteristic'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePlayerCharacteristic>>, {id: string;data: Characteristic}> = (props) => {
          const {id,data} = props ?? {};

          return  updatePlayerCharacteristic(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePlayerCharacteristicMutationResult = NonNullable<Awaited<ReturnType<typeof updatePlayerCharacteristic>>>
    export type UpdatePlayerCharacteristicMutationBody = Characteristic
    export type UpdatePlayerCharacteristicMutationError = AxiosError<unknown>

    export const useUpdatePlayerCharacteristic = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlayerCharacteristic>>, TError,{id: string;data: Characteristic}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePlayerCharacteristic>>,
        TError,
        {id: string;data: Characteristic},
        TContext
      > => {

      const mutationOptions = getUpdatePlayerCharacteristicMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const updatePlayerSkill = (
    id: string,
    playerSkill: PlayerSkill, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.patch(
      `/api/players/api/players/creation/${id}/skills/`,
      playerSkill,options
    );
  }



export const getUpdatePlayerSkillMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlayerSkill>>, TError,{id: string;data: PlayerSkill}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updatePlayerSkill>>, TError,{id: string;data: PlayerSkill}, TContext> => {

const mutationKey = ['updatePlayerSkill'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePlayerSkill>>, {id: string;data: PlayerSkill}> = (props) => {
          const {id,data} = props ?? {};

          return  updatePlayerSkill(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePlayerSkillMutationResult = NonNullable<Awaited<ReturnType<typeof updatePlayerSkill>>>
    export type UpdatePlayerSkillMutationBody = PlayerSkill
    export type UpdatePlayerSkillMutationError = AxiosError<unknown>

    export const useUpdatePlayerSkill = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlayerSkill>>, TError,{id: string;data: PlayerSkill}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePlayerSkill>>,
        TError,
        {id: string;data: PlayerSkill},
        TContext
      > => {

      const mutationOptions = getUpdatePlayerSkillMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const updatePlayerTalent = (
    id: string,
    talent: Talent, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.patch(
      `/api/players/api/players/creation/${id}/talents/`,
      talent,options
    );
  }



export const getUpdatePlayerTalentMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlayerTalent>>, TError,{id: string;data: Talent}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updatePlayerTalent>>, TError,{id: string;data: Talent}, TContext> => {

const mutationKey = ['updatePlayerTalent'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePlayerTalent>>, {id: string;data: Talent}> = (props) => {
          const {id,data} = props ?? {};

          return  updatePlayerTalent(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePlayerTalentMutationResult = NonNullable<Awaited<ReturnType<typeof updatePlayerTalent>>>
    export type UpdatePlayerTalentMutationBody = Talent
    export type UpdatePlayerTalentMutationError = AxiosError<unknown>

    export const useUpdatePlayerTalent = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlayerTalent>>, TError,{id: string;data: Talent}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePlayerTalent>>,
        TError,
        {id: string;data: Talent},
        TContext
      > => {

      const mutationOptions = getUpdatePlayerTalentMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const updatePlayerCareer = (
    id: string,
    career: Career, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PlayerResponse>> => {
    
    
    return axios.default.patch(
      `/api/players/creation/${id}/careers/`,
      career,options
    );
  }



export const getUpdatePlayerCareerMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlayerCareer>>, TError,{id: string;data: Career}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updatePlayerCareer>>, TError,{id: string;data: Career}, TContext> => {

const mutationKey = ['updatePlayerCareer'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePlayerCareer>>, {id: string;data: Career}> = (props) => {
          const {id,data} = props ?? {};

          return  updatePlayerCareer(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePlayerCareerMutationResult = NonNullable<Awaited<ReturnType<typeof updatePlayerCareer>>>
    export type UpdatePlayerCareerMutationBody = Career
    export type UpdatePlayerCareerMutationError = AxiosError<unknown>

    export const useUpdatePlayerCareer = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlayerCareer>>, TError,{id: string;data: Career}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePlayerCareer>>,
        TError,
        {id: string;data: Career},
        TContext
      > => {

      const mutationOptions = getUpdatePlayerCareerMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const updatePlayerCareerSkills = (
    id: string,
    playerSkill: PlayerSkill[], options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PlayerResponse>> => {
    
    
    return axios.default.patch(
      `/api/players/creation/${id}/careers/skills/`,
      playerSkill,options
    );
  }



export const getUpdatePlayerCareerSkillsMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlayerCareerSkills>>, TError,{id: string;data: PlayerSkill[]}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updatePlayerCareerSkills>>, TError,{id: string;data: PlayerSkill[]}, TContext> => {

const mutationKey = ['updatePlayerCareerSkills'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePlayerCareerSkills>>, {id: string;data: PlayerSkill[]}> = (props) => {
          const {id,data} = props ?? {};

          return  updatePlayerCareerSkills(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePlayerCareerSkillsMutationResult = NonNullable<Awaited<ReturnType<typeof updatePlayerCareerSkills>>>
    export type UpdatePlayerCareerSkillsMutationBody = PlayerSkill[]
    export type UpdatePlayerCareerSkillsMutationError = AxiosError<unknown>

    export const useUpdatePlayerCareerSkills = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlayerCareerSkills>>, TError,{id: string;data: PlayerSkill[]}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePlayerCareerSkills>>,
        TError,
        {id: string;data: PlayerSkill[]},
        TContext
      > => {

      const mutationOptions = getUpdatePlayerCareerSkillsMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Fetch a player by name
 */
export const getPlayer = (
    name: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PlayerResponse>> => {
    
    
    return axios.default.get(
      `/api/players/${name}`,options
    );
  }


export const getGetPlayerQueryKey = (name?: string,) => {
    return [`/api/players/${name}`] as const;
    }

    
export const getGetPlayerQueryOptions = <TData = Awaited<ReturnType<typeof getPlayer>>, TError = AxiosError<unknown>>(name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlayer>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPlayerQueryKey(name);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlayer>>> = ({ signal }) => getPlayer(name, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(name), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPlayer>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPlayerQueryResult = NonNullable<Awaited<ReturnType<typeof getPlayer>>>
export type GetPlayerQueryError = AxiosError<unknown>


export function useGetPlayer<TData = Awaited<ReturnType<typeof getPlayer>>, TError = AxiosError<unknown>>(
 name: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlayer>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlayer>>,
          TError,
          Awaited<ReturnType<typeof getPlayer>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlayer<TData = Awaited<ReturnType<typeof getPlayer>>, TError = AxiosError<unknown>>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlayer>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlayer>>,
          TError,
          Awaited<ReturnType<typeof getPlayer>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlayer<TData = Awaited<ReturnType<typeof getPlayer>>, TError = AxiosError<unknown>>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlayer>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch a player by name
 */

export function useGetPlayer<TData = Awaited<ReturnType<typeof getPlayer>>, TError = AxiosError<unknown>>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlayer>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPlayerQueryOptions(name,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update a player
 */
export const updatePlayer = (
    name: string,
    player: Player, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PlayerResponse>> => {
    
    
    return axios.default.put(
      `/api/players/${name}`,
      player,options
    );
  }



export const getUpdatePlayerMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlayer>>, TError,{name: string;data: Player}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updatePlayer>>, TError,{name: string;data: Player}, TContext> => {

const mutationKey = ['updatePlayer'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePlayer>>, {name: string;data: Player}> = (props) => {
          const {name,data} = props ?? {};

          return  updatePlayer(name,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePlayerMutationResult = NonNullable<Awaited<ReturnType<typeof updatePlayer>>>
    export type UpdatePlayerMutationBody = Player
    export type UpdatePlayerMutationError = AxiosError<unknown>

    /**
 * @summary Update a player
 */
export const useUpdatePlayer = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlayer>>, TError,{name: string;data: Player}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePlayer>>,
        TError,
        {name: string;data: Player},
        TContext
      > => {

      const mutationOptions = getUpdatePlayerMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    