/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Activation } from "./activation";
import type { Cost } from "./cost";
import type { Limit } from "./limit";
import type { Action } from "./action";
import type { Modifier } from "./modifier";

export interface Ability {
  name: string;
  description: string;
  activation: Activation;
  cost: Cost;
  limit: Limit;
  action: Action;
  modifiers: Modifier[];
}
