/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { AbilityActivation } from './abilityActivation';
import type { Cost } from './cost';
import type { Limit } from './limit';
import type { Action } from './action';
import type { Modifier } from './modifier';

export interface Ability {
  name?: string;
  description?: string;
  activation?: AbilityActivation;
  cost?: Cost;
  limit?: Limit;
  action?: Action;
  modifiers?: Modifier[];
}
