/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { AbilityModifiers } from './abilityModifiers';
import type { Activation } from './activation';
import type { Cost } from './cost';
import type { Limit } from './limit';
import type { StatModifiers } from './statModifiers';

export interface Ability {
  name: string;
  description: string;
  activation: Activation;
  cost: Cost;
  limit: Limit;
  statModifiers: StatModifiers;
  abilityModifiers: AbilityModifiers;
}
