/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { DiceModifier } from './diceModifier';
import type { EnvironmentModifier } from './environmentModifier';
import type { HealEffect } from './healEffect';
import type { ResultsModifier } from './resultsModifier';

export interface AbilityModifiers {
  /** Dice added to or removed from rolls based on check context */
  diceModifiers: DiceModifier[];
  /** Results added to or removed from rolls based on check context */
  resultsModifiers: ResultsModifier[];
  /** Healing applied to wounds or strain when the ability is used */
  healEffects: HealEffect[];
  /** Terrain or environmental effects ignored by this character */
  environmentModifiers: EnvironmentModifier[];
  /** Critical Injury result is treated as 01 when this ability is triggered */
  criticalInjuryCountAsOne: boolean;
  /** A second move maneuver costs no strain */
  freeMoveManeuver: boolean;
  /** Moves a Story Point from the GM pool to the players' pool */
  moveStoryPoint: boolean;
}
