/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { ActorSkill } from "./actorSkill";
import type { Difficulty } from "./difficulty";
import type { RangeBand } from "./rangeBand";

export interface Action {
  skill: ActorSkill;
  difficulty: Difficulty;
  opposedSkill: ActorSkill;
  rangeBand: RangeBand;
}
