/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { ActionType } from './actionType';
import type { DiceModifier } from './diceModifier';
import type { Difficulty } from './difficulty';
import type { RangeBand } from './rangeBand';
import type { ResultsModifier } from './resultsModifier';
import type { Skill } from './skill';
import type { Target } from './target';

export interface Action {
  /** The category of action being taken during structured combat */
  type: ActionType;
  /** The skill used to resolve this action; null for unarmed combat using default stats */
  skill?: Skill;
  /** Whether the check is opposed by the target's own skill roll rather than a fixed difficulty */
  opposed: boolean;
  /** Base difficulty of the check when not opposed (ignored when opposed=true) */
  difficulty?: Difficulty;
  /** Who or what this action targets */
  target: Target;
  /** Maximum range band at which this action can be performed */
  range?: RangeBand;
  /** Base damage dealt on a successful hit (Combat Checks only; 0 indicates no direct damage) */
  damage?: number;
  /** Whether the actor's Brawn characteristic is added to the damage value */
  brawnBonus?: boolean;
  /** Critical rating of the attack (Combat Checks only; 0 means the attack cannot trigger a Critical Injury) */
  critical?: number;
  /** Dice added to or removed from the check's pool */
  diceModifiers?: DiceModifier[];
  /** Fixed result symbols added to the outcome of the check */
  resultsModifiers?: ResultsModifier[];
}
