/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type ActionRangeBand =
  (typeof ActionRangeBand)[keyof typeof ActionRangeBand];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActionRangeBand = {
  Engaged: "Engaged",
  Short: "Short",
  Medium: "Medium",
  Long: "Long",
  Extreme: "Extreme",
  Strategic: "Strategic",
} as const;
