/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type Activation = (typeof Activation)[keyof typeof Activation];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Activation = {
  Passive: "Passive",
  "Active_(Action)": "Active (Action)",
  "Active_(Maneuver)": "Active (Maneuver)",
  "Active_(Incidental)": "Active (Incidental)",
  "Active_(Incidental,_Out_of_Turn)": "Active (Incidental, Out of Turn)",
} as const;
