/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type ActorArmorSlot = typeof ActorArmorSlot[keyof typeof ActorArmorSlot];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActorArmorSlot = {
  Main_Hand: 'Main Hand',
  Off_Hand: 'Off Hand',
  Both_Hands: 'Both Hands',
  Body: 'Body',
  None: 'None',
} as const;
