/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type ActorSkillType = typeof ActorSkillType[keyof typeof ActorSkillType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActorSkillType = {
  General: 'General',
  Magic: 'Magic',
  Combat: 'Combat',
  Social: 'Social',
  Knowledge: 'Knowledge',
} as const;
