/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { ActorArmorSlot } from './actorArmorSlot';
import type { ActorArmorType } from './actorArmorType';
import type { EquipmentQuality } from './equipmentQuality';
import type { Modifier } from './modifier';

export interface ActorArmor {
  id: string;
  /** @minLength 1 */
  name: string;
  type: ActorArmorType;
  description: string;
  /** @minimum 0 */
  price: number;
  restricted: boolean;
  /** @minimum 0 */
  encumbrance: number;
  /**
   * @minimum 0
   * @maximum 10
   */
  rarity: number;
  modifiers: Modifier[];
  qualities: EquipmentQuality[];
  /** @minimum 0 */
  soak: number;
  /** @minimum 0 */
  defense: number;
  slot: ActorArmorSlot;
}
