/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type ActorType = typeof ActorType[keyof typeof ActorType];


export const ActorType = {
  Minion: 'Minion',
  Rival: 'Rival',
  Nemesis: 'Nemesis',
  Player: 'Player',
} as const;
