/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { ActorWeaponSlot } from './actorWeaponSlot';
import type { ActorWeaponType } from './actorWeaponType';
import type { EquipmentQuality } from './equipmentQuality';
import type { Modifier } from './modifier';
import type { RangeBand } from './rangeBand';
import type { Skill } from './skill';

export interface ActorWeapon {
  id: string;
  /** @minLength 1 */
  name: string;
  type: ActorWeaponType;
  description: string;
  /** @minimum 0 */
  price: number;
  restricted: boolean;
  /** @minimum 0 */
  encumbrance: number;
  /**
   * @minimum 0
   * @maximum 10
   */
  rarity: number;
  modifiers: Modifier[];
  qualities: EquipmentQuality[];
  /** @minimum 0 */
  damage: number;
  skill: Skill;
  /** @minimum 1 */
  critical: number;
  range: RangeBand;
  brawn: boolean;
  /**
   * @minimum 1
   * @maximum 2
   */
  hands: number;
  slot: ActorWeaponSlot;
}
