/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type ActorArmorSlot = typeof ActorArmorSlot[keyof typeof ActorArmorSlot];


export const ActorArmorSlot = {
  Body: 'Body',
  None: 'None',
} as const;
