/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Modifier } from "./modifier";
import type { EquipmentQuality } from "./equipmentQuality";
import type { Skill } from "./skill";
import type { RangeBand } from "./rangeBand";
import type { ActorWeaponSlot } from "./actorWeaponSlot";

export interface ActorWeapon {
  id: string;
  /** @minLength 1 */
  name: string;
  description: string;
  /** @minimum 0 */
  price: number;
  restricted: boolean;
  /** @minimum 0 */
  encumbrance: number;
  /**
   * @minimum 0
   * @maximum 10
   */
  rarity: number;
  modifiers: Modifier[];
  qualities: EquipmentQuality[];
  damage?: number;
  skill?: Skill;
  critical?: number;
  range?: RangeBand;
  brawn?: boolean;
  hands?: number;
  slot: ActorWeaponSlot;
}
