/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { ActorSkillCharacteristic } from './actorSkillCharacteristic';
import type { ActorSkillType } from './actorSkillType';

export interface ActorSkill {
  id?: string;
  /** @minLength 1 */
  name: string;
  /** The type of Characteristic */
  characteristic?: ActorSkillCharacteristic;
  type?: ActorSkillType;
  initiative: boolean;
  ranks?: number;
}
