/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type ActorWeaponSlot = typeof ActorWeaponSlot[keyof typeof ActorWeaponSlot];


export const ActorWeaponSlot = {
  Main_Hand: 'Main Hand',
  Off_Hand: 'Off Hand',
  Both_Hands: 'Both Hands',
  None: 'None',
} as const;
