/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { CharacteristicType } from './characteristicType';
import type { SkillType } from './skillType';

export interface ActorSkill {
  id: string;
  /** @minLength 1 */
  name: string;
  characteristic: CharacteristicType;
  type: SkillType;
  initiative: boolean;
  summary: string;
  description: string;
  ranks: number;
}
