/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type ActorType = typeof ActorType[keyof typeof ActorType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActorType = {
  Minion: 'Minion',
  Rival: 'Rival',
  Nemesis: 'Nemesis',
  Player: 'Player',
} as const;
