/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { ActorArmor } from './actorArmor';
import type { ActorType } from './actorType';
import type { ActorWeapon } from './actorWeapon';
import type { Characteristic } from './characteristic';
import type { Error } from './error';
import type { OldStats } from './oldStats';

export interface Actor {
  id: string;
  /** @minLength 1 */
  name: string;
  type: ActorType;
  brawn: Characteristic;
  agility: Characteristic;
  intellect: Characteristic;
  cunning: Characteristic;
  willpower: Characteristic;
  presence: Characteristic;
  wounds: OldStats;
  /** @minimum 0 */
  soak: number;
  /** @minimum 0 */
  melee: number;
  /** @minimum 0 */
  ranged: number;
  weapons: ActorWeapon[];
  armors: ActorArmor[];
  errors?: Error[];
}
