/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type ActorTalentActivation = typeof ActorTalentActivation[keyof typeof ActorTalentActivation];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActorTalentActivation = {
  Passive: 'Passive',
  'Active_(Action)': 'Active (Action)',
  'Active_(Maneuver)': 'Active (Maneuver)',
  'Active_(Incidental)': 'Active (Incidental)',
  'Active_(Incidental,_Out_of_Turn)': 'Active (Incidental, Out of Turn)',
} as const;
