/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type ActorWeaponType = typeof ActorWeaponType[keyof typeof ActorWeaponType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActorWeaponType = {
  Weapon: 'Weapon',
  Armor: 'Armor',
  Gear: 'Gear',
} as const;
