/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type ActorWeaponRange = typeof ActorWeaponRange[keyof typeof ActorWeaponRange];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActorWeaponRange = {
  Engaged: 'Engaged',
  Short: 'Short',
  Medium: 'Medium',
  Long: 'Long',
  Extreme: 'Extreme',
  Strategic: 'Strategic',
} as const;
