/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type ActorArmorType = typeof ActorArmorType[keyof typeof ActorArmorType];


export const ActorArmorType = {
  Weapon: 'Weapon',
  Armor: 'Armor',
  Gear: 'Gear',
} as const;
