/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Modifier } from './modifier';
import type { EquipmentQuality } from './equipmentQuality';
import type { ActorArmorSlot } from './actorArmorSlot';

export interface ActorArmor {
  id?: string;
  name?: string;
  description?: string;
  price?: number;
  restricted?: boolean;
  encumbrance?: number;
  rarity?: number;
  modifiers?: Modifier[];
  qualities?: EquipmentQuality[];
  soak?: number;
  defense?: number;
  slot?: ActorArmorSlot;
}
