/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type ActorTalentTier = typeof ActorTalentTier[keyof typeof ActorTalentTier];


export const ActorTalentTier = {
  First: 'First',
  Second: 'Second',
  Third: 'Third',
  Fourth: 'Fourth',
  Fifth: 'Fifth',
} as const;
