/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type ActorArmorType =
  (typeof ActorArmorType)[keyof typeof ActorArmorType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActorArmorType = {
  Weapon: "Weapon",
  Armor: "Armor",
  Gear: "Gear",
} as const;
