/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { AdversaryEquipment } from './adversaryEquipment';
import type { AdversaryRatings } from './adversaryRatings';
import type { AdversarySkill } from './adversarySkill';
import type { AdversaryTemplateType } from './adversaryTemplateType';
import type { Characteristics } from './characteristics';
import type { DerivedStats } from './derivedStats';
import type { Error } from './error';

/**
 * Setting-specific adversaries such as Nemeses, Rivals, and Minions
 */
export interface AdversaryTemplate {
  id: string;
  /** @minLength 1 */
  name: string;
  /** The description of the adversary */
  description: string;
  /** The type of adversary */
  type: AdversaryTemplateType;
  /** The characteristics of the adversary */
  characteristics: Characteristics;
  /** The stats of the adversary */
  derivedStats: DerivedStats;
  /** Weapons, armor, and gear of the adversary */
  equipment: AdversaryEquipment;
  /** Adversary Skills */
  skills: AdversarySkill[];
  /** Adversary Ratings */
  ratings: AdversaryRatings;
  errors?: Error[];
}
