/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * The type of adversary
 */
export type AdversaryTemplateType = typeof AdversaryTemplateType[keyof typeof AdversaryTemplateType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdversaryTemplateType = {
  Minion: 'Minion',
  Rival: 'Rival',
  Nemesis: 'Nemesis',
} as const;
