/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { ArmorInstance } from './armorInstance';
import type { GearInstance } from './gearInstance';
import type { WeaponInstance } from './weaponInstance';

export interface AdversaryEquipment {
  weapons?: WeaponInstance[];
  equippedArmor?: ArmorInstance;
  otherGear?: GearInstance[];
}
