/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { WeaponInstance } from "./weaponInstance";
import type { ArmorInstance } from "./armorInstance";
import type { GearInstance } from "./gearInstance";

export interface AdversaryEquipment {
  weapons?: WeaponInstance[];
  equippedArmor?: ArmorInstance;
  otherGear?: GearInstance[];
}
