/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { AdversaryEquipment } from './adversaryEquipment';
import type { AdversaryRatings } from './adversaryRatings';
import type { AdversaryTemplateType } from './adversaryTemplateType';
import type { Characteristics } from './characteristics';
import type { DerivedStats } from './derivedStats';
import type { GenesysError } from './genesysError';
import type { Motivation } from './motivation';
import type { RankedSkill } from './rankedSkill';

/**
 * Setting-specific adversaries such as Nemeses, Rivals, and Minions
 */
export interface AdversaryTemplate {
  id: string;
  /** @minLength 1 */
  name: string;
  /** The description of the adversary */
  description: string;
  /** The type of adversary */
  type: AdversaryTemplateType;
  /** The characteristics of the adversary */
  characteristics: Characteristics;
  /** The stats of the adversary */
  derivedStats: DerivedStats;
  /** Weapons, armor, and gear of the adversary */
  equipment: AdversaryEquipment;
  /** Adversary Skills */
  skills: RankedSkill[];
  /** Adversary Ratings */
  ratings: AdversaryRatings;
  size: number;
  /** Adversary motivations */
  motivations: Motivation[];
  errors?: GenesysError[];
}
