/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { ItemInstance } from './itemInstance';

export interface AdversaryEquipment {
  weapons: ItemInstance[];
  equippedArmor: ItemInstance;
  otherGear: ItemInstance[];
}
