/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * The type of adversary
 */
export type AdversaryTemplateType = typeof AdversaryTemplateType[keyof typeof AdversaryTemplateType];


export const AdversaryTemplateType = {
  Minion: 'Minion',
  Rival: 'Rival',
  Nemesis: 'Nemesis',
} as const;
