/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { AdversarySkillCharacteristic } from './adversarySkillCharacteristic';
import type { SkillType } from './skillType';

/**
 * Setting-specific skills on adversary
 */
export interface AdversarySkill {
  id: string;
  /** @minLength 1 */
  name: string;
  /** The type of Characteristic */
  characteristic: AdversarySkillCharacteristic;
  type: SkillType;
  initiative: boolean;
  /** @minimum 0 */
  ranks: number;
  group: boolean;
}
