/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export interface AdversaryRatings {
  /** @minimum 1 */
  combat: number;
  /** @minimum 1 */
  social: number;
  /** @minimum 1 */
  general: number;
}
