/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Characteristics } from "./characteristics";

/**
 * Setting-specific adversaries such as Nemeses, Rivals, and Minions
 */
export interface AdversaryTemplate {
  id: string;
  /** @minLength 1 */
  name: string;
  /** The characteristics of the adversary */
  characteristics: Characteristics;
}
