/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { CharacteristicType } from './characteristicType';
import type { SkillType } from './skillType';

/**
 * Setting-specific skills on adversary
 */
export interface AdversarySkill {
  id: string;
  /** @minLength 1 */
  name: string;
  characteristic: CharacteristicType;
  type: SkillType;
  initiative: boolean;
  /** @minimum 0 */
  ranks: number;
  group: boolean;
}
