/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export interface AfterEncounterEffect {
  /** Wounds suffered at the end of the encounter */
  wounds: number;
  /** Strain suffered at the end of the encounter */
  strain: number;
}
