/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Skill } from './skill';
import type { SkillType } from './skillType';

/**
 * A skill entry granted by an archetype during character creation
 */
export interface ArchetypeSkill {
  /** The skill granted. Null when playerChoice is true and the player selects the skill themselves. */
  skill?: Skill;
  /**
     * Number of starting ranks in this skill granted by the archetype before experience is spent
     * @minimum 1
     * @maximum 2
     */
  startingRanks: number;
  /**
     * Maximum rank this skill may be trained to during character creation
     * @minimum 2
     * @maximum 3
     */
  maxRank: number;
  /** When true, the skill must be a non-career skill (not among the character's career skills). May be combined with playerChoice=true, in which case the player must choose from non-career skills. */
  nonCareer?: boolean;
  /** When true, the player selects which skill to apply these ranks to at character creation (the 'skill' field will be null). Use 'nonCareer=true' to restrict the choice to non-career skills, and 'requiredSkillType' to restrict the choice to a specific skill type. */
  playerChoice?: boolean;
  /** When playerChoice is true, restricts the type of skill the player may choose (e.g. KNOWLEDGE for a knowledge-only free choice). Null means any skill type is allowed. */
  requiredSkillType?: SkillType;
}
