/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Skill } from './skill';
import type { Ability } from './ability';

export interface Archetype {
  id?: string;
  /** @minLength 1 */
  name: string;
  description?: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  brawn?: number;
  /**
   * @minimum 1
   * @maximum 5
   */
  agility?: number;
  /**
   * @minimum 1
   * @maximum 5
   */
  intellect?: number;
  /**
   * @minimum 1
   * @maximum 5
   */
  cunning?: number;
  /**
   * @minimum 1
   * @maximum 5
   */
  willpower?: number;
  /**
   * @minimum 1
   * @maximum 5
   */
  presence?: number;
  wounds?: number;
  strain?: number;
  /** @minimum 65 */
  experience?: number;
  skill?: Skill;
  abilities?: Ability[];
}
