/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Equipment } from './equipment';

export type Armor = Equipment & {
  /** @minimum 0 */
  soak?: number;
  /** @minimum 0 */
  defense?: number;
} & Required<Pick<Equipment & {
  /** @minimum 0 */
  soak?: number;
  /** @minimum 0 */
  defense?: number;
}, 'defense' | 'soak'>>;
