/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Attribute } from './attribute';
import type { ItemTemplate } from './itemTemplate';

export type ArmorTemplate = ItemTemplate & {
  soak?: Attribute;
  defense?: Attribute;
} & Required<Pick<ItemTemplate & {
  soak?: Attribute;
  defense?: Attribute;
}, 'defense' | 'soak'>>;
