/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { EquipmentQuality } from './equipmentQuality';

export interface Armor {
  id: string;
  /** @minLength 1 */
  name: string;
  /**
     * Soak bonus granted by this armor
     * @minimum 0
     */
  soak: number;
  /**
     * Defense bonus granted by this armor
     * @minimum 0
     */
  defense: number;
  /** Active qualities on this armor */
  qualities?: EquipmentQuality[];
}
