/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Equipment } from './equipment';
import type { ArmorAllOf } from './armorAllOf';

export type Armor = Equipment & ArmorAllOf & Required<Pick<Equipment & ArmorAllOf, 'defense' | 'soak'>>;
