/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type ArmorAllOf = {
  /** @minimum 0 */
  soak?: number;
  /** @minimum 0 */
  defense?: number;
};
