/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Defensive Attribute
 */
export interface Attribute {
  /**
     * Current value of the Defensive Attribute
     * @minimum 0
     */
  current: number;
  /**
     * Base value of the Defensive Attribute
     * @minimum 0
     */
  base: number;
}
