/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Archetype } from "./archetype";
import type { Career } from "./career";
import type { Skill } from "./skill";

export interface CampaignCompendium {
  /** Custom species or archetypes */
  archetypes: Archetype[];
  /** Custom careers and career skills */
  careers: Career[];
  /** Setting-specific skills */
  skills: Skill[];
}
