/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Party } from "./party";
import type { Session } from "./session";

export interface Campaign {
  id: string;
  /** @minLength 1 */
  name: string;
  party: Party;
  sessions: Session[];
  current: boolean;
  active: boolean;
  talentIds: string[];
  skillIds: string[];
  sceneIds: string[];
}
