/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { AdversaryTemplate } from './adversaryTemplate';
import type { Archetype } from './archetype';
import type { Career } from './career';
import type { CriticalInjury } from './criticalInjury';
import type { ItemTemplate } from './itemTemplate';
import type { Quality } from './quality';
import type { Skill } from './skill';
import type { Talent } from './talent';

export interface CampaignCompendium {
  /** Custom species or archetypes */
  archetypes: Archetype[];
  /** Custom careers and career skills */
  careers: Career[];
  /** Setting-specific skills */
  skills: Skill[];
  /** Setting-specific talents */
  talents: Talent[];
  /** Setting-specific weapons, armor, and gear */
  items: ItemTemplate[];
  /** Setting-specific Nemeses, Rivals, and Minions */
  adversaries: AdversaryTemplate[];
  /** Setting-specific equipment qualities */
  qualities: Quality[];
  /** Setting-specific critical injuries */
  criticalInjuries: CriticalInjury[];
}
