/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type CampaignSessionStatus = typeof CampaignSessionStatus[keyof typeof CampaignSessionStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CampaignSessionStatus = {
  Planning: 'Planning',
  Ready: 'Ready',
  Active: 'Active',
  Resolved: 'Resolved',
} as const;
