/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type CampaignEncounterType = typeof CampaignEncounterType[keyof typeof CampaignEncounterType];


export const CampaignEncounterType = {
  Combat: 'Combat',
  Social: 'Social',
  General: 'General',
} as const;
