/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { CampaignScene } from './campaignScene';
import type { CampaignSessionStatus } from './campaignSessionStatus';
import type { Party } from './party';

/**
 * The root entity for a VTT Campaign setting
 */
export interface CampaignSession {
  id: string;
  campaignId: string;
  sessionDate: string;
  scenes: CampaignScene[];
  /** Party state during Session */
  party: Party;
  status: CampaignSessionStatus;
  /** @minimum 0 */
  player: number;
  /** @minimum 0 */
  gm: number;
}
