/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { CampaignEncounter } from './campaignEncounter';

export interface CampaignScene {
  sceneId: string;
  name: string;
  mapUrl: string;
  encounters: CampaignEncounter[];
}
