/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { ItemTemplate } from "./itemTemplate";
import type { ArmorTemplate } from "./armorTemplate";
import type { GearTemplate } from "./gearTemplate";
import type { WeaponTemplate } from "./weaponTemplate";

export type CampaignCompendiumItemsItem =
  | ItemTemplate
  | ArmorTemplate
  | GearTemplate
  | WeaponTemplate;
