/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Party } from "./party";
import type { CampaignCompendium } from "./campaignCompendium";

/**
 * The root entity for a VTT Campaign setting
 */
export interface Campaign {
  id: string;
  /** @minLength 1 */
  name: string;
  party: Party;
  /** GM-defined setting bible */
  compendium: CampaignCompendium;
}
