/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { CampaignEncounterEncounterStatus } from './campaignEncounterEncounterStatus';
import type { CampaignEncounterEncounterType } from './campaignEncounterEncounterType';
import type { Party } from './party';

export interface CampaignEncounter {
  encounterType: CampaignEncounterEncounterType;
  encounterStatus: CampaignEncounterEncounterStatus;
  encounterId: string;
  name: string;
  npcIds: string[];
  initiativeOrder: string[];
  /** Party state during Encounter */
  party: Party;
}
