/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type CampaignEncounterStatus = typeof CampaignEncounterStatus[keyof typeof CampaignEncounterStatus];


export const CampaignEncounterStatus = {
  Building: 'Building',
  Ready: 'Ready',
  Active: 'Active',
  Resolved: 'Resolved',
} as const;
