/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { AdversaryTemplate } from './adversaryTemplate';
import type { CampaignEncounterStatus } from './campaignEncounterStatus';
import type { CampaignEncounterType } from './campaignEncounterType';
import type { InitiativeSlot } from './initiativeSlot';
import type { Party } from './party';

export interface CampaignEncounter {
  type: CampaignEncounterType;
  status: CampaignEncounterStatus;
  encounterId: string;
  name: string;
  npcIds: AdversaryTemplate[];
  initiativeOrder: InitiativeSlot[];
  /** Party state during Encounter */
  party: Party;
}
