/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { AdversaryTemplate } from './adversaryTemplate';
import type { CampaignEncounterEncounterStatus } from './campaignEncounterEncounterStatus';
import type { CampaignEncounterEncounterType } from './campaignEncounterEncounterType';
import type { InitiativeSlot } from './initiativeSlot';
import type { Party } from './party';

export interface CampaignEncounter {
  encounterType: CampaignEncounterEncounterType;
  encounterStatus: CampaignEncounterEncounterStatus;
  encounterId: string;
  name: string;
  npcIds: AdversaryTemplate[];
  initiativeOrder: InitiativeSlot[];
  /** Party state during Encounter */
  party: Party;
}
