/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Skill } from './skill';

export interface Career {
  id?: string;
  /** @minLength 1 */
  name: string;
  /**
   * @minItems 0
   * @maxItems 8
   */
  skills?: Skill[];
}
