/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Skill } from './skill';
import type { StartingGearChoice } from './startingGearChoice';
import type { StartingMoney } from './startingMoney';

/**
 * Setting-specific careers for player characters
 */
export interface Career {
  id: string;
  /** @minLength 1 */
  name: string;
  /**
     * @minItems 0
     * @maxItems 8
     */
  skills: Skill[];
  /** Optional starting gear entries for this career; each entry offers one or more items to choose from */
  startingGear?: StartingGearChoice[];
  /** Optional starting money awarded to characters of this career */
  startingMoney?: StartingMoney;
}
