/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * The type of Characteristic
 */
export type CharacteristicType = typeof CharacteristicType[keyof typeof CharacteristicType];


export const CharacteristicType = {
  Brawn: 'Brawn',
  Agility: 'Agility',
  Intellect: 'Intellect',
  Cunning: 'Cunning',
  Willpower: 'Willpower',
  Presence: 'Presence',
} as const;
