/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Characteristic Stat
 */
export interface Characteristic {
  /**
   * Current value of the Characteristic
   * @minimum 1
   */
  current: number;
  /**
   * Base value of the Characteristic
   * @minimum 1
   */
  base: number;
}
