/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { CharacteristicType } from './characteristicType';

/**
 * Characteristic Stat
 */
export interface Characteristic {
  /** Characteristic type */
  type?: CharacteristicType;
  /**
   * Current value of the Characteristic
   * @minimum 1
   */
  current?: number;
}
