/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { CharacteristicType } from './characteristicType';

export interface CharacteristicModifier {
  /** The characteristic to modify */
  characteristic: CharacteristicType;
  /** The amount to modify the characteristic by; positive values increase, negative values decrease */
  amount: number;
}
