/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Characteristic } from './characteristic';

/**
 * Characteristic Stat
 */
export interface Characteristics {
  brawn: Characteristic;
  agility: Characteristic;
  intellect: Characteristic;
  cunning: Characteristic;
  willpower: Characteristic;
  presence: Characteristic;
}
