/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Actor type
 */
export type CharacterResponseType = typeof CharacterResponseType[keyof typeof CharacterResponseType];


export const CharacterResponseType = {
  Minion: 'Minion',
  Rival: 'Rival',
  Nemesis: 'Nemesis',
  Player: 'Player',
} as const;
