/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { CharacterResponseType } from './characterResponseType';
import type { Characteristic } from './characteristic';
import type { Stats } from './stats';
import type { ActorWeapon } from './actorWeapon';
import type { ActorArmor } from './actorArmor';
import type { Ability } from './ability';
import type { ActorTalent } from './actorTalent';
import type { CriticalInjury } from './criticalInjury';
import type { ActorSkill } from './actorSkill';
import type { StatusEffect } from './statusEffect';

/**
 * Response DTO representing any character type: Player, Nemesis, Rival, or MinionGroup
 */
export interface CharacterResponse {
  /** Globally unique ID for this character */
  id?: string;
  /** Character's name */
  name?: string;
  /** Actor type */
  type?: CharacterResponseType;
  /** Brawn characteristic */
  brawn?: Characteristic;
  /** Agility characteristic */
  agility?: Characteristic;
  /** Intellect characteristic */
  intellect?: Characteristic;
  /** Cunning characteristic */
  cunning?: Characteristic;
  /** Willpower characteristic */
  willpower?: Characteristic;
  /** Presence characteristic */
  presence?: Characteristic;
  /** Wound stats (current and max) */
  wounds?: Stats;
  /** Strain stats (current and max) */
  strain?: Stats;
  /** Soak value */
  soak?: number;
  /** Melee defense value */
  melee?: number;
  /** Ranged defense value */
  ranged?: number;
  /** Encumbrance threshold */
  encumbrance?: number;
  /** Equipped weapons */
  weapons?: ActorWeapon[];
  /** Equipped armor pieces */
  armors?: ActorArmor[];
  /** Special abilities the character possesses */
  abilities?: Ability[];
  /** Talents associated with the character */
  talents?: ActorTalent[];
  /** Current critical injuries */
  injuries?: CriticalInjury[];
  /** Skill ratings and expertise */
  skills?: ActorSkill[];
  /** Status effects currently active */
  effects?: StatusEffect[];
  /** Number of Minions in the Minion Group */
  size?: number;
}
