/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type CheckTarget = typeof CheckTarget[keyof typeof CheckTarget];


export const CheckTarget = {
  Self: 'Self',
  Opponent: 'Opponent',
} as const;
