/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export interface CombatLogEntry {
  rollSessionId?: string;
  timestamp?: string;
  finalSummary?: string;
  narrativeLines?: string[];
}
