/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { CostType } from './costType';

export interface Cost {
  type: CostType;
  /** @minimum 0 */
  amount: number;
}
