/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Difficulty } from "./difficulty";
import type { Modifier } from "./modifier";

export interface CriticalInjury {
  id: string;
  name: string;
  description: string;
  severity: Difficulty;
  min: number;
  max: number;
  modifiers: Modifier[];
}
