/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { CriticalInjuryStats } from './criticalInjuryStats';
import type { Difficulty } from './difficulty';

/**
 * Setting-specific Critical Injuries
 */
export interface CriticalInjury {
  id: string;
  name: string;
  description: string;
  severity: Difficulty;
  min: number;
  max: number;
  stats: CriticalInjuryStats;
}
