/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type DefenseType = typeof DefenseType[keyof typeof DefenseType];


export const DefenseType = {
  Melee: 'Melee',
  Ranged: 'Ranged',
} as const;
