/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Attribute } from './attribute';
import type { Threshold } from './threshold';

/**
 * Stats
 */
export interface DerivedStats {
  woundThreshold: Threshold;
  strainThreshold: Threshold;
  melee: Attribute;
  ranged: Attribute;
  soak: Attribute;
}
