/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Threshold } from "./threshold";
import type { Attribute } from "./attribute";

/**
 * Stats
 */
export interface DerivedStats {
  woundThreshold: Threshold;
  strainThreshold: Threshold;
  defense: Attribute;
  soak: Attribute;
}
