/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { DicePool } from './dicePool';
import type { DiceRollType } from './diceRollType';
import type { NetResult } from './netResult';
import type { RawDieResult } from './rawDieResult';
import type { RollTotals } from './rollTotals';

export interface DiceRoll {
  id?: string;
  /** @minLength 1 */
  encounterId: string;
  /** @minLength 1 */
  participantId: string;
  slotId?: string;
  /** @minLength 1 */
  participantName: string;
  /** @minimum 1 */
  round?: number;
  rollType: DiceRollType;
  dicePool: DicePool;
  rawResults?: RawDieResult[];
  totals: RollTotals;
  netResult: NetResult;
  skillUsed?: string;
  actionId?: string;
  notes?: string;
  createdAt?: string;
}
