/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { CheckContext } from './checkContext';
import type { DiceType } from './diceType';
import type { Skill } from './skill';
import type { SkillType } from './skillType';
import type { Target } from './target';

export interface DiceModifier {
  /** The type of die to add to the pool */
  diceType: DiceType;
  /** Number of dice to add */
  amount: number;
  /** The kind of check that triggers this modifier */
  checkContext: CheckContext;
  /** Restricts this modifier to checks of a particular skill type; null means any skill type */
  skillType?: SkillType;
  /** Restricts this modifier to a specific skill; null means any skill matching skill */
  skill?: Skill;
  /** Whether this modifier applies to the character's own rolls or to rolls made against them */
  checkTarget: Target;
}
