/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export interface DicePool {
  /**
   * Number of ability dice in the pool
   * @minimum 0
   */
  ability: number;
  /**
   * Number of proficiency dice in the pool
   * @minimum 0
   */
  proficiency: number;
  /**
   * Number of difficulty dice in the pool
   * @minimum 0
   */
  difficulty: number;
  /**
   * Number of challenge dice in the pool
   * @minimum 0
   */
  challenge: number;
  /**
   * Number of boost dice in the pool
   * @minimum 0
   */
  boost: number;
  /**
   * Number of setback dice in the pool
   * @minimum 0
   */
  setback: number;
}
