/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { DicePool } from './dicePool';
import type { DiceRollType } from './diceRollType';

export interface DiceRollRequest {
  /** @minLength 1 */
  encounterId: string;
  /** @minLength 1 */
  participantId: string;
  /** @minLength 1 */
  participantName: string;
  slotId?: string;
  /** @minimum 1 */
  round?: number;
  rollType: DiceRollType;
  dicePool: DicePool;
  skillUsed?: string;
  actionId?: string;
  notes?: string;
}
