/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { CheckContext } from './checkContext';
import type { CheckTarget } from './checkTarget';
import type { DiceType } from './diceType';
import type { SkillType } from './skillType';

export interface DiceModifier {
  /** The type of die to add to the pool */
  diceType: DiceType;
  /** Number of dice to add */
  amount: number;
  /** The kind of check that triggers this modifier */
  checkContext: CheckContext;
  /** Restricts this modifier to checks of a particular skill type; null means any skill type */
  skillType?: SkillType;
  /** Whether this modifier applies to the character's own rolls or to rolls made against them */
  checkTarget: CheckTarget;
}
