/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type DiceType = typeof DiceType[keyof typeof DiceType];


export const DiceType = {
  Boost: 'Boost',
  Setback: 'Setback',
  Ability: 'Ability',
  Difficulty: 'Difficulty',
  Proficiency: 'Proficiency',
  Challenge: 'Challenge',
} as const;
