/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type DiceRollType = typeof DiceRollType[keyof typeof DiceRollType];


export const DiceRollType = {
  Initiative: 'Initiative',
  Action: 'Action',
  Skill: 'Skill',
  Combat: 'Combat',
} as const;
