/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type DiceSymbol = typeof DiceSymbol[keyof typeof DiceSymbol];


export const DiceSymbol = {
  Success: 'Success',
  Advantage: 'Advantage',
  Triumph: 'Triumph',
  Failure: 'Failure',
  Threat: 'Threat',
  Despair: 'Despair',
  Blank: 'Blank',
} as const;
