/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type DiceType = typeof DiceType[keyof typeof DiceType];


export const DiceType = {
  Boost: 'Boost',
  Setback: 'Setback',
  Advantage: 'Advantage',
  Threat: 'Threat',
  Success: 'Success',
  Failure: 'Failure',
  Triumph: 'Triumph',
  Despair: 'Despair',
} as const;
