/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type Difficulty = typeof Difficulty[keyof typeof Difficulty];


export const Difficulty = {
  Easy: 'Easy',
  Average: 'Average',
  Hard: 'Hard',
  Daunting: 'Daunting',
  Formidable: 'Formidable',
} as const;
