/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type Duration = typeof Duration[keyof typeof Duration];


export const Duration = {
  Permanent: 'Permanent',
  Scene: 'Scene',
  Encounter: 'Encounter',
} as const;
