/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type Duration = typeof Duration[keyof typeof Duration];


export const Duration = {
  Permanent: 'Permanent',
  Scene: 'Scene',
  Encounter: 'Encounter',
  End_of_Next_Turn: 'End of Next Turn',
  Next_Check: 'Next Check',
  Next_Turn: 'Next Turn',
} as const;
