/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export interface Effect {
  name?: string;
  description?: string;
  increase?: number;
}
