/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type EndEncounter200 = {[key: string]: string};
