/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { EnvironmentEffect } from './environmentEffect';
import type { EnvironmentType } from './environmentType';

export interface EnvironmentModifier {
  /** The environment in which this modifier applies */
  environment: EnvironmentType;
  /** The effect or immunity granted in that environment */
  effect: EnvironmentEffect;
}
