/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Modifier } from "./modifier";

export interface EquipmentQuality {
  id: string;
  name: string;
  description: string;
  cost: number;
  armor: boolean;
  weapon: boolean;
  modifiers: Modifier[];
  /** @minimum 0 */
  ranks: number;
}
