/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type EquipmentType = (typeof EquipmentType)[keyof typeof EquipmentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EquipmentType = {
  Weapon: "Weapon",
  Armor: "Armor",
  Gear: "Gear",
} as const;
