/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { ItemTemplate } from './itemTemplate';

export interface Equipment {
  weapons: ItemTemplate[];
  equippedArmor: ItemTemplate;
  otherGear: ItemTemplate[];
}
