/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { QualityStats } from './qualityStats';

export interface EquipmentQuality {
  id: string;
  name: string;
  description: string;
  cost: number;
  armor: boolean;
  weapon: boolean;
  stats: QualityStats;
  /** @minimum 1 */
  ranks: number;
}
