/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type EquipmentTypeProperty = typeof EquipmentTypeProperty[keyof typeof EquipmentTypeProperty];


export const EquipmentTypeProperty = {
  Weapon: 'Weapon',
  Armor: 'Armor',
  Gear: 'Gear',
} as const;
