/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export interface Error {
  message?: string;
}
