/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { FieldError } from "./fieldError";
import type { ObjectError } from "./objectError";

export interface Errors {
  objectName?: string;
  nestedPath?: string;
  fieldError?: FieldError;
  allErrors?: ObjectError[];
  fieldErrorCount?: number;
  globalError?: ObjectError;
  fieldErrors?: FieldError[];
  globalErrors?: ObjectError[];
  errorCount?: number;
  globalErrorCount?: number;
}
