/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export interface Experience {
  /** @minimum 0 */
  initial: number;
  /** @minimum 0 */
  total: number;
  /** @minimum 0 */
  available: number;
}
