/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export interface FieldError {
  codes?: string[];
  arguments?: unknown[];
  defaultMessage?: string;
  objectName?: string;
  field?: string;
  rejectedValue?: unknown;
  bindingFailure?: boolean;
  code?: string;
}
