/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Equipment } from "./equipment";
import type { GearAllOf } from "./gearAllOf";

export type Gear = Equipment & GearAllOf;
