/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { ItemTemplate } from './itemTemplate';

export type GearTemplate = ItemTemplate & {
  /** @minimum 1 */
  amount?: number;
} & Required<Pick<ItemTemplate & {
  /** @minimum 1 */
  amount?: number;
}, 'amount'>>;
