/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export interface GearInstance {
  id: string;
  /** @minLength 1 */
  name: string;
  description: string;
  restricted: boolean;
  /** @minimum 0 */
  encumbrance: number;
}
