/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { DiceModifier } from './diceModifier';
import type { ResultsModifier } from './resultsModifier';
import type { StatModifiers } from './statModifiers';
import type { UpgradeModifier } from './upgradeModifier';

export interface GearModifiers {
  /** Dice added to or removed from rolls based on check context and optional skill filter */
  diceModifiers: DiceModifier[];
  /** Fixed results added to rolls based on check context and optional skill filter */
  resultsModifiers: ResultsModifier[];
  /** Dice upgrades applied to rolls, with optional duration limit */
  upgradeModifiers: UpgradeModifier[];
  /** Flat stat bonuses applied while this item is equipped */
  statModifiers: StatModifiers;
  /** Overrides the item's encumbrance while worn; null means use the item's normal encumbrance */
  equippedEncumbranceOverride?: number;
}
