/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export interface Gear {
  id: string;
  /** @minLength 1 */
  name: string;
  /** Description of the gear item */
  description?: string;
  /** Encumbrance value of the item */
  encumbrance?: number;
}
