/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type GearTemplateAllOf = {
  /** @minimum 1 */
  amount?: number;
};
