/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Skill } from "./skill";
import type { RangeBand } from "./rangeBand";

export type GearAllOf = {
  skill?: Skill;
  amount?: number;
  range?: RangeBand;
};
