/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Equipment } from './equipment';
import type { RangeBand } from './rangeBand';
import type { Skill } from './skill';

export type Gear = Equipment & {
  skill?: Skill;
  amount?: number;
  range?: RangeBand;
};
