/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type GearModifiersAppliedStatusEffectsItem = typeof GearModifiersAppliedStatusEffectsItem[keyof typeof GearModifiersAppliedStatusEffectsItem];


export const GearModifiersAppliedStatusEffectsItem = {
  Disoriented: 'Disoriented',
  Immobilized: 'Immobilized',
  Staggered: 'Staggered',
} as const;
