/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { ItemTemplate } from "./itemTemplate";
import type { GearTemplateAllOf } from "./gearTemplateAllOf";

export type GearTemplate = ItemTemplate &
  GearTemplateAllOf &
  Required<Pick<ItemTemplate & GearTemplateAllOf, "amount">>;
