/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { AfterEncounterEffect } from './afterEncounterEffect';
import type { CharacteristicModifier } from './characteristicModifier';
import type { DiceModifier } from './diceModifier';
import type { GearModifiersAppliedStatusEffectsItem } from './gearModifiersAppliedStatusEffectsItem';
import type { HealEffect } from './healEffect';
import type { RangeBand } from './rangeBand';
import type { ResultsModifier } from './resultsModifier';
import type { SkillRankModifier } from './skillRankModifier';
import type { StatModifiers } from './statModifiers';
import type { UpgradeModifier } from './upgradeModifier';

export interface GearModifiers {
  /** Dice added to or removed from rolls based on check context and optional skill filter */
  diceModifiers: DiceModifier[];
  /** Fixed results added to rolls based on check context and optional skill filter */
  resultsModifiers: ResultsModifier[];
  /** Dice upgrades applied to rolls, with optional duration limit */
  upgradeModifiers: UpgradeModifier[];
  /** Characteristic bonuses applied while this item is equipped */
  characteristicModifiers: CharacteristicModifier[];
  /** Skill rank bonuses applied while this item is equipped */
  skillRankModifiers: SkillRankModifier[];
  /** Flat stat bonuses applied while this item is equipped */
  statModifiers: StatModifiers;
  /** Healing applied to wounds or strain when this item is used */
  healEffects: HealEffect[];
  /** Status effects applied to the character when this item is used */
  appliedStatusEffects: GearModifiersAppliedStatusEffectsItem[];
  /** Wounds and strain suffered at the end of the encounter; null means no after-encounter penalty */
  afterEncounterEffect?: AfterEncounterEffect;
  /** Character ignores Critical Injury penalties on skill checks for the encounter */
  ignoreCriticalInjuryPenalties: boolean;
  /** Each subsequent use of this item on the same day heals one fewer wound (min 0) */
  diminishingReturnsHealing: boolean;
  /** Overrides the item's encumbrance while worn; null means use the item's normal encumbrance */
  equippedEncumbranceOverride?: number;
  /** The effective range of this gear item's effect; null means no range limitation */
  range?: RangeBand;
}
