/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Lore } from "./lore";
import type { Organization } from "./organization";

export type GetAllLore200Item = Lore | Organization;
