/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type GetModifiers200Item = typeof GetModifiers200Item[keyof typeof GetModifiers200Item];


export const GetModifiers200Item = {
  Default: 'Default',
  Decrease_Critical_Injury: 'Decrease Critical Injury',
  Increase_Critical_Injury: 'Increase Critical Injury',
  Reset_Critical_Injury: 'Reset Critical Injury',
  Suffer_Strain: 'Suffer Strain',
  Deal_Strain_Damage: 'Deal Strain Damage',
  Increase_Melee_Defense: 'Increase Melee Defense',
  Increase_Ranged_Defense: 'Increase Ranged Defense',
  Increase_Soak: 'Increase Soak',
  Ignore_Soak: 'Ignore Soak',
  Recharge: 'Recharge',
} as const;
