/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { GroupSkillCharacteristic } from './groupSkillCharacteristic';
import type { SkillType } from './skillType';

export interface GroupSkill {
  id: string;
  /** @minLength 1 */
  name: string;
  /** The type of Characteristic */
  characteristic: GroupSkillCharacteristic;
  type: SkillType;
  initiative: boolean;
  group: boolean;
}
