/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type HealTarget = typeof HealTarget[keyof typeof HealTarget];


export const HealTarget = {
  Wounds: 'Wounds',
  Strain: 'Strain',
} as const;
