/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { CharacteristicType } from './characteristicType';
import type { HealSource } from './healSource';
import type { HealTarget } from './healTarget';

export interface HealEffect {
  /** What is healed — wounds or strain */
  target: HealTarget;
  /** What determines the amount healed */
  source: HealSource;
  /** Amount healed when source is FIXED */
  amount?: number;
  /** Characteristic whose current rank equals the amount healed; only used when source is CHARACTERISTIC */
  characteristic?: CharacteristicType;
}
