/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { AdversaryTemplate } from './adversaryTemplate';
import type { InitiativeSlotType } from './initiativeSlotType';
import type { PlayerCharacter } from './playerCharacter';

export interface InitiativeSlot {
  type: InitiativeSlotType;
  adversaryTemplate: AdversaryTemplate;
  playerCharacter: PlayerCharacter;
  initiative?: string;
}
