/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { AdversaryTemplate } from './adversaryTemplate';
import type { InitiativeSlotResults } from './initiativeSlotResults';
import type { InitiativeSlotType } from './initiativeSlotType';
import type { PlayerCharacter } from './playerCharacter';

export interface InitiativeSlot {
  type: InitiativeSlotType;
  adversaryTemplate: AdversaryTemplate;
  playerCharacter: PlayerCharacter;
  results: InitiativeSlotResults;
  initiative?: string;
}
