/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Request to roll initiative for a single participant
 */
export interface InitiativeRollRequest {
  /**
     * ID of the participant rolling initiative (must be registered in the encounter)
     * @minLength 1
     */
  participantId: string;
  /**
     * Name of the initiative skill to use (e.g. 'Cool' or 'Vigilance'). The skill must be present in the participant's skill list with initiative=true.
     * @minLength 1
     */
  initiativeSkillName: string;
  /** Extra boost (blue) dice from situational bonuses */
  boostDice?: number;
  /** Extra setback (black) dice from situational penalties */
  setbackDice?: number;
}
