/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type ItemTemplateType = typeof ItemTemplateType[keyof typeof ItemTemplateType];


export const ItemTemplateType = {
  Weapon: 'Weapon',
  Armor: 'Armor',
  Gear: 'Gear',
} as const;
