/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Attribute } from './attribute';
import type { EquipmentQuality } from './equipmentQuality';
import type { ItemTemplateType } from './itemTemplateType';
import type { Modifier } from './modifier';
import type { RangeBand } from './rangeBand';
import type { Skill } from './skill';

/**
 * Base item template
 */
export interface ItemTemplate {
  id: string;
  /** @minLength 1 */
  name: string;
  type: ItemTemplateType;
  description: string;
  /** @minimum 0 */
  price: number;
  restricted: boolean;
  /** @minimum 0 */
  encumbrance: number;
  /**
   * @minimum 0
   * @maximum 10
   */
  rarity: number;
  modifiers: Modifier[];
  qualities: EquipmentQuality[];
  /** @minimum 1 */
  amount: number;
  /** The skill associated with the weapon */
  skill: Skill;
  /**
   * The damage of the weapon
   * @minimum 0
   */
  damage: number;
  /**
   * The critical rating of the weapon
   * @minimum 1
   */
  critical: number;
  /** The range band of the weapon */
  range: RangeBand;
  /** Whether the weapon damage is increased by Brawn */
  brawn: boolean;
  soak: Attribute;
  defense: Attribute;
}
