/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { EquipmentQuality } from './equipmentQuality';
import type { ItemTemplateType } from './itemTemplateType';
import type { Modifier } from './modifier';

/**
 * Base item template
 */
export interface ItemTemplate {
  id: string;
  /** @minLength 1 */
  name: string;
  type: ItemTemplateType;
  description: string;
  /** @minimum 0 */
  price: number;
  restricted: boolean;
  /** @minimum 0 */
  encumbrance: number;
  /**
   * @minimum 0
   * @maximum 10
   */
  rarity: number;
  modifiers: Modifier[];
  qualities: EquipmentQuality[];
}
