/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Instance of an Item
 */
export interface ItemInstance {
  id?: string;
  templateId?: string;
  ownerId?: string;
  quantity?: number;
}
