/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Setting-specific weapons, armor, and gear
 */
export interface ItemTemplate {
  id: string;
  /** @minLength 1 */
  name: string;
}
