/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { LimitType } from './limitType';

export interface Limit {
  type: LimitType;
  /** @minimum 0 */
  limit: number;
}
