/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type LimitType = typeof LimitType[keyof typeof LimitType];


export const LimitType = {
  None: 'None',
  Per_Round: 'Per Round',
  Per_Encounter: 'Per Encounter',
  Per_Session: 'Per Session',
} as const;
