/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { LoreType } from "./loreType";

export interface Lore {
  id: string;
  name: string;
  type: LoreType;
  description: string;
}
