/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type LoreType = typeof LoreType[keyof typeof LoreType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoreType = {
  Organization: 'Organization',
} as const;
