/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type LoreType = typeof LoreType[keyof typeof LoreType];


export const LoreType = {
  Organization: 'Organization',
} as const;
