/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { DefenseModifier } from './defenseModifier';
import type { DiceModifier } from './diceModifier';
import type { Duration } from './duration';
import type { ResultsModifier } from './resultsModifier';
import type { Skill } from './skill';
import type { Target } from './target';

export interface Maneuver {
  /** Who this maneuver targets (Self, Engaged Ally, etc.) */
  target: Target;
  /** How long the effects of this maneuver last */
  duration: Duration;
  /** Whether multiple uses of this maneuver stack (e.g., assist maneuver) */
  stackable?: boolean;
  /** Maximum number of targets affected. Ignored when targetCountSkill is set. */
  maxTargets?: number;
  /** When set, the number of targets equals the performer's current rank in this skill (e.g., Leadership for Coordinated Assault). Overrides maxTargets. */
  targetCountSkill?: Skill;
  /** When true, the effective range increases by one band per additional rank in the talent. */
  rangeScalesWithRank?: boolean;
  /** Dice added to affected characters' pools. checkTarget=SELF applies to the performer; checkTarget=OPPONENT applies to the maneuver's target(s). */
  diceModifiers?: DiceModifier[];
  /** Fixed result symbols added to affected characters' checks. checkTarget=SELF applies to the performer; checkTarget=OPPONENT applies to the maneuver's target(s). */
  resultsModifiers?: ResultsModifier[];
  /** Defense bonuses or penalties applied when this maneuver is performed. */
  defenseModifiers?: DefenseModifier[];
}
