/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { MinionType } from "./minionType";
import type { Characteristic } from "./characteristic";
import type { Stats } from "./stats";
import type { ActorWeapon } from "./actorWeapon";
import type { ActorArmor } from "./actorArmor";
import type { Error } from "./error";
import type { ActorTalent } from "./actorTalent";
import type { Ability } from "./ability";
import type { GroupSkill } from "./groupSkill";

export interface Minion {
  id: string;
  /** @minLength 1 */
  name: string;
  type: MinionType;
  brawn: Characteristic;
  agility: Characteristic;
  intellect: Characteristic;
  cunning: Characteristic;
  willpower: Characteristic;
  presence: Characteristic;
  wounds: Stats;
  /** @minimum 0 */
  soak: number;
  /** @minimum 0 */
  melee: number;
  /** @minimum 0 */
  ranged: number;
  weapons: ActorWeapon[];
  armors: ActorArmor[];
  errors?: Error[];
  /** @minimum 1 */
  combat: number;
  /** @minimum 1 */
  social: number;
  /** @minimum 1 */
  general: number;
  talents: ActorTalent[];
  abilities: Ability[];
  skills: GroupSkill[];
}
