/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Ability } from './ability';
import type { Actor } from './actor';
import type { ActorTalent } from './actorTalent';
import type { GroupSkill } from './groupSkill';

export type Minion = Actor & {
  /** @minimum 1 */
  combat?: number;
  /** @minimum 1 */
  social?: number;
  /** @minimum 1 */
  general?: number;
  talents?: ActorTalent[];
  abilities?: Ability[];
  skills?: GroupSkill[];
} & Required<Pick<Actor & {
  /** @minimum 1 */
  combat?: number;
  /** @minimum 1 */
  social?: number;
  /** @minimum 1 */
  general?: number;
  talents?: ActorTalent[];
  abilities?: Ability[];
  skills?: GroupSkill[];
}, 'abilities' | 'combat' | 'general' | 'skills' | 'social' | 'talents'>>;
