/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Actor } from "./actor";
import type { MinionAllOf } from "./minionAllOf";

export type Minion = Actor &
  MinionAllOf &
  Required<
    Pick<
      Actor & MinionAllOf,
      "abilities" | "combat" | "general" | "skills" | "social" | "talents"
    >
  >;
