/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { ModifierType } from './modifierType';

export interface Modifier {
  type: ModifierType;
  ranks: number;
}
