/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type ModifierType = typeof ModifierType[keyof typeof ModifierType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModifierType = {
  Default: 'Default',
  Decrease_Critical_Injury: 'Decrease Critical Injury',
  Increase_Critical_Injury: 'Increase Critical Injury',
  Reset_Critical_Injury: 'Reset Critical Injury',
  Suffer_Strain: 'Suffer Strain',
  Deal_Strain_Damage: 'Deal Strain Damage',
  Increase_Melee_Defense: 'Increase Melee Defense',
  Increase_Ranged_Defense: 'Increase Ranged Defense',
  Increase_Soak: 'Increase Soak',
  Ignore_Soak: 'Ignore Soak',
  Recharge: 'Recharge',
} as const;
