/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Actor } from './actor';
import type { NemesisAllOf } from './nemesisAllOf';

export type Nemesis = Actor & NemesisAllOf & Required<Pick<Actor & NemesisAllOf, 'abilities' | 'combat' | 'general' | 'injuries' | 'skills' | 'social' | 'strain' | 'talents'>>;
