/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type NemesisType = (typeof NemesisType)[keyof typeof NemesisType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NemesisType = {
  Minion: "Minion",
  Rival: "Rival",
  Nemesis: "Nemesis",
  Player: "Player",
} as const;
