/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Ability } from './ability';
import type { Actor } from './actor';
import type { ActorSkill } from './actorSkill';
import type { ActorTalent } from './actorTalent';
import type { CriticalInjury } from './criticalInjury';
import type { OldStats } from './oldStats';

export type Nemesis = Actor & {
  /** @minimum 1 */
  combat?: number;
  /** @minimum 1 */
  social?: number;
  /** @minimum 1 */
  general?: number;
  talents?: ActorTalent[];
  abilities?: Ability[];
  skills?: ActorSkill[];
  strain?: OldStats;
  injuries?: CriticalInjury[];
} & Required<Pick<Actor & {
  /** @minimum 1 */
  combat?: number;
  /** @minimum 1 */
  social?: number;
  /** @minimum 1 */
  general?: number;
  talents?: ActorTalent[];
  abilities?: Ability[];
  skills?: ActorSkill[];
  strain?: OldStats;
  injuries?: CriticalInjury[];
}, 'abilities' | 'combat' | 'general' | 'injuries' | 'skills' | 'social' | 'strain' | 'talents'>>;
