/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { ActorTalent } from "./actorTalent";
import type { Ability } from "./ability";
import type { ActorSkill } from "./actorSkill";
import type { OldStats } from "./oldStats";
import type { CriticalInjury } from "./criticalInjury";

export type NemesisAllOf = {
  /** @minimum 1 */
  combat?: number;
  /** @minimum 1 */
  social?: number;
  /** @minimum 1 */
  general?: number;
  talents?: ActorTalent[];
  abilities?: Ability[];
  skills?: ActorSkill[];
  strain?: OldStats;
  injuries?: CriticalInjury[];
};
