/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export interface NetResult {
  netSuccess?: number;
  netAdvantage?: number;
  success?: boolean;
  triumph?: boolean;
  despair?: boolean;
}
