/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export interface ObjectError {
  codes?: string[];
  arguments?: unknown[];
  defaultMessage?: string;
  objectName?: string;
  code?: string;
}
