/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { OldPlayerSkillCharacteristic } from './oldPlayerSkillCharacteristic';
import type { SkillType } from './skillType';

/**
 * Player Skill Data
 */
export interface OldPlayerSkill {
  id: string;
  /** @minLength 1 */
  name: string;
  /** The type of Characteristic */
  characteristic: OldPlayerSkillCharacteristic;
  type: SkillType;
  initiative: boolean;
  /** @minimum 0 */
  ranks: number;
  career: boolean;
}
