/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { CharacteristicType } from './characteristicType';
import type { SkillType } from './skillType';

/**
 * Player Skill Data
 */
export interface OldPlayerSkill {
  id: string;
  /** @minLength 1 */
  name: string;
  characteristic: CharacteristicType;
  type: SkillType;
  initiative: boolean;
  /** A short summary of the skill */
  summary: string;
  /** A detailed description of the skill */
  description: string;
  /** @minimum 0 */
  ranks: number;
  career: boolean;
}
