/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { OldStatsType } from './oldStatsType';

export interface OldStats {
  /** @minimum 0 */
  current: number;
  /** @minimum 0 */
  threshold: number;
  type: OldStatsType;
}
