/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type OldStatsType = (typeof OldStatsType)[keyof typeof OldStatsType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OldStatsType = {
  Wounds: "Wounds",
  Strain: "Strain",
} as const;
