/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type OldStatsType = typeof OldStatsType[keyof typeof OldStatsType];


export const OldStatsType = {
  Wounds: 'Wounds',
  Strain: 'Strain',
} as const;
