/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Lore } from './lore';
import type { OrganizationAllOf } from './organizationAllOf';

export type Organization = Lore & OrganizationAllOf & Required<Pick<Lore & OrganizationAllOf, 'disbanded' | 'founded' | 'membersName' | 'nickname' | 'orgType'>>;
