/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type OrganizationOrgType = typeof OrganizationOrgType[keyof typeof OrganizationOrgType];


export const OrganizationOrgType = {
  Political: 'Political',
  Social: 'Social',
  Religious: 'Religious',
  Military: 'Military',
  Academic: 'Academic',
} as const;
