/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type OrganizationAllOfOrgType =
  (typeof OrganizationAllOfOrgType)[keyof typeof OrganizationAllOfOrgType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrganizationAllOfOrgType = {
  Political: "Political",
  Social: "Social",
  Religious: "Religious",
  Military: "Military",
  Academic: "Academic",
} as const;
