/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { LoreType } from './loreType';
import type { OrganizationOrgType } from './organizationOrgType';

export interface Organization {
  id: string;
  name: string;
  type: LoreType;
  description: string;
  orgType: OrganizationOrgType;
  founded: number;
  disbanded: number;
  nickname: string;
  membersName: string;
}
