/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { OrganizationAllOfOrgType } from "./organizationAllOfOrgType";

export type OrganizationAllOf = {
  orgType?: OrganizationAllOfOrgType;
  founded?: number;
  disbanded?: number;
  nickname?: string;
  membersName?: string;
};
