/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Lore } from './lore';

export type Organization = Lore & {
  orgType?: 'Political' | 'Social' | 'Religious' | 'Military' | 'Academic';
  founded?: number;
  disbanded?: number;
  nickname?: string;
  membersName?: string;
} & Required<Pick<Lore & {
  orgType?: 'Political' | 'Social' | 'Religious' | 'Military' | 'Academic';
  founded?: number;
  disbanded?: number;
  nickname?: string;
  membersName?: string;
}, 'disbanded' | 'founded' | 'membersName' | 'nickname' | 'orgType'>>;
