/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type OrganizationType =
  (typeof OrganizationType)[keyof typeof OrganizationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrganizationType = {
  Organization: "Organization",
} as const;
