/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Whether this participant is a player character or non-player character
 */
export type ParticipantType = typeof ParticipantType[keyof typeof ParticipantType];


export const ParticipantType = {
  pc: 'pc',
  npc: 'npc',
} as const;
