/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { PlayerCharacter } from './playerCharacter';

export interface Party {
  /** @minItems 1 */
  players: PlayerCharacter[];
}
