/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Player } from './player';

export interface Party {
  /** @minItems 1 */
  players: Player[];
}
