/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Armor } from './armor';
import type { Gear } from './gear';
import type { Weapon } from './weapon';

export interface ParticipantEquipment {
  equippedWeapons: Weapon[];
  weapons: Weapon[];
  equippedArmor: Armor;
  armor: Armor[];
  otherGear: Gear[];
}
