/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Ability } from './ability';
import type { Characteristics } from './characteristics';
import type { DerivedStats } from './derivedStats';
import type { ParticipantEquipment } from './participantEquipment';
import type { ParticipantType } from './participantType';
import type { RankedSkill } from './rankedSkill';
import type { StatusEffect } from './statusEffect';

/**
 * A participant (PC or NPC) taking part in an encounter
 */
export interface Participant {
  id: string;
  /** @minLength 1 */
  name: string;
  /** Whether this participant is a player character or non-player character */
  type: ParticipantType;
  /** The characteristics of the player */
  characteristics: Characteristics;
  /** The stats of the player */
  derivedStats: DerivedStats;
  /** Active status effects currently applied to this participant */
  statusEffects: StatusEffect[];
  /** URL of the participant's portrait or token image */
  imageUrl?: string;
  /** Free-text notes about this participant */
  notes?: string;
  /** The items currently in the participant's possession */
  equipment: ParticipantEquipment;
  /** Special abilities available to this participant */
  abilities: Ability[];
  /** Skills possessed by this participant */
  skills: RankedSkill[];
}
