/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type PlayerSkillType =
  (typeof PlayerSkillType)[keyof typeof PlayerSkillType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlayerSkillType = {
  General: "General",
  Magic: "Magic",
  Combat: "Combat",
  Social: "Social",
  Knowledge: "Knowledge",
} as const;
