/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * The type of Characteristic
 */
export type PlayerSkillCharacteristic = typeof PlayerSkillCharacteristic[keyof typeof PlayerSkillCharacteristic];


export const PlayerSkillCharacteristic = {
  Brawn: 'Brawn',
  Agility: 'Agility',
  Intellect: 'Intellect',
  Cunning: 'Cunning',
  Willpower: 'Willpower',
  Presence: 'Presence',
} as const;
