/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { AdversarySkill } from './adversarySkill';
import type { Characteristics } from './characteristics';
import type { DerivedStats } from './derivedStats';
import type { PlayerEquipment } from './playerEquipment';

/**
 * Setting-specific Player for a specific Campaign
 */
export interface PlayerCharacter {
  id: string;
  /** @minLength 1 */
  name: string;
  /** The characteristics of the player */
  characteristics: Characteristics;
  /** The stats of the player */
  derivedStats: DerivedStats;
  /** Weapons, armor, and gear of the player */
  equipment: PlayerEquipment;
  /** Adversary Skills */
  skills: AdversarySkill[];
}
