/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { PlayerSkillCharacteristic } from './playerSkillCharacteristic';
import type { PlayerSkillType } from './playerSkillType';

/**
 * Player Skill Data
 */
export interface PlayerSkill {
  id?: string;
  /** @minLength 1 */
  name: string;
  /** The type of Characteristic */
  characteristic?: PlayerSkillCharacteristic;
  type?: PlayerSkillType;
  initiative: boolean;
  /** @minimum 0 */
  ranks?: number;
  career: boolean;
}
