/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

/** @deprecated Use {@link Motivation} from './motivation' directly */
export type { Motivation as PlayerMotivation } from './motivation';
