/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Actor } from "./actor";
import type { PlayerAllOf } from "./playerAllOf";

export type Player = Actor &
  PlayerAllOf &
  Required<
    Pick<
      Actor & PlayerAllOf,
      | "archetype"
      | "career"
      | "encumbrance"
      | "experience"
      | "injuries"
      | "skills"
      | "strain"
      | "talents"
    >
  >;
