/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { PlayerResponseErrorsItemCause } from "./playerResponseErrorsItemCause";
import type { PlayerResponseErrorsItemStackTraceItem } from "./playerResponseErrorsItemStackTraceItem";
import type { PlayerResponseErrorsItemSuppressedItem } from "./playerResponseErrorsItemSuppressedItem";

export type PlayerResponseErrorsItem = {
  cause?: PlayerResponseErrorsItemCause;
  stackTrace?: PlayerResponseErrorsItemStackTraceItem[];
  message?: string;
  suppressed?: PlayerResponseErrorsItemSuppressedItem[];
  localizedMessage?: string;
};
