/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Actor } from './actor';
import type { ActorTalent } from './actorTalent';
import type { Archetype } from './archetype';
import type { Career } from './career';
import type { CriticalInjury } from './criticalInjury';
import type { Experience } from './experience';
import type { OldPlayerSkill } from './oldPlayerSkill';
import type { OldStats } from './oldStats';

export type Player = Actor & {
  strain?: OldStats;
  encumbrance?: number;
  experience?: Experience;
  career?: Career;
  archetype?: Archetype;
  talents?: ActorTalent[];
  skills?: OldPlayerSkill[];
  injuries?: CriticalInjury[];
  creation?: boolean;
  ownerId?: string;
} & Required<Pick<Actor & {
  strain?: OldStats;
  encumbrance?: number;
  experience?: Experience;
  career?: Career;
  archetype?: Archetype;
  talents?: ActorTalent[];
  skills?: OldPlayerSkill[];
  injuries?: CriticalInjury[];
  creation?: boolean;
  ownerId?: string;
}, 'archetype' | 'career' | 'encumbrance' | 'experience' | 'injuries' | 'ownerId' | 'skills' | 'strain' | 'talents'>>;
