/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Actor type
 */
export type PlayerResponseType = typeof PlayerResponseType[keyof typeof PlayerResponseType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlayerResponseType = {
  Minion: 'Minion',
  Rival: 'Rival',
  Nemesis: 'Nemesis',
  Player: 'Player',
} as const;
