/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type PlayerType = typeof PlayerType[keyof typeof PlayerType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlayerType = {
  Minion: 'Minion',
  Rival: 'Rival',
  Nemesis: 'Nemesis',
  Player: 'Player',
} as const;
