/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { OldStats } from "./oldStats";
import type { Experience } from "./experience";
import type { Career } from "./career";
import type { Archetype } from "./archetype";
import type { ActorTalent } from "./actorTalent";
import type { PlayerSkill } from "./playerSkill";
import type { CriticalInjury } from "./criticalInjury";

export type PlayerAllOf = {
  strain?: OldStats;
  encumbrance?: number;
  experience?: Experience;
  career?: Career;
  archetype?: Archetype;
  talents?: ActorTalent[];
  skills?: PlayerSkill[];
  injuries?: CriticalInjury[];
  creation?: boolean;
};
