/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Archetype } from './archetype';
import type { Career } from './career';
import type { Characteristics } from './characteristics';
import type { DerivedStats } from './derivedStats';
import type { PlayerEquipment } from './playerEquipment';
import type { PlayerSkill } from './playerSkill';

/**
 * Setting-specific Player for a specific Campaign
 */
export interface PlayerCharacter {
  id: string;
  /** @minLength 1 */
  name: string;
  /** Player archetype */
  archetype: Archetype;
  /** Player career */
  career: Career;
  /** The characteristics of the player */
  characteristics: Characteristics;
  /** The stats of the player */
  derivedStats: DerivedStats;
  /** Weapons, armor, and gear of the player */
  equipment: PlayerEquipment;
  /** Player Skills */
  skills: PlayerSkill[];
}
