/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { QualityStats } from './qualityStats';

/**
 * Setting-specific Qualities
 */
export interface Quality {
  id: string;
  name: string;
  description: string;
  cost: number;
  armor: boolean;
  weapon: boolean;
  stats: QualityStats;
}
