/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export interface QualityStats {
  criticalInjury: number;
  ignoreSoak: number;
  damageOverTime: number;
  areaDamage: number;
  soak: number;
  meleeDefense: number;
  rangedDefense: number;
  ensnare: boolean;
  stun: boolean;
  disorient: boolean;
  description?: string;
}
