/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { DiceModifier } from './diceModifier';
import type { ResultsModifier } from './resultsModifier';

export interface QualityStats {
  criticalInjury: number;
  ignoreSoak: number;
  damageOverTime: number;
  areaDamage: number;
  soak: number;
  meleeDefense: number;
  rangedDefense: number;
  ensnare: boolean;
  stun: boolean;
  diceModifier: DiceModifier;
  resultsModifier: ResultsModifier;
  description?: string;
}
