/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type RangeBand = (typeof RangeBand)[keyof typeof RangeBand];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RangeBand = {
  Engaged: "Engaged",
  Short: "Short",
  Medium: "Medium",
  Long: "Long",
  Extreme: "Extreme",
  Strategic: "Strategic",
} as const;
