/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { DiceSymbol } from './diceSymbol';

export interface RawDieResult {
  dieType?: string;
  faceRolled?: number;
  symbols?: DiceSymbol[];
}
