/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { CheckContext } from './checkContext';
import type { GenesysSymbolResults } from './genesysSymbolResults';
import type { Skill } from './skill';
import type { SkillType } from './skillType';
import type { Target } from './target';

export interface ResultsModifier {
  /** The fixed results added to the pool */
  results: GenesysSymbolResults;
  /** The kind of check that triggers this modifier */
  checkContext: CheckContext;
  /** Restricts this modifier to checks of a particular skill type; null means any skill type */
  skillType?: SkillType;
  /** Whether this modifier applies to the character's own rolls or to rolls made against them */
  checkTarget: Target;
  /** Restricts this modifier to a specific skill; null means any skill matching skillType */
  skill?: Skill;
}
