/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type ResultType = typeof ResultType[keyof typeof ResultType];


export const ResultType = {
  Success: 'Success',
  Advantage: 'Advantage',
  Triumph: 'Triumph',
  Failure: 'Failure',
  Threat: 'Threat',
  Despair: 'Despair',
} as const;
