/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Actor } from './actor';
import type { RivalAllOf } from './rivalAllOf';

export type Rival = Actor & RivalAllOf & Required<Pick<Actor & RivalAllOf, 'abilities' | 'combat' | 'general' | 'injuries' | 'skills' | 'social' | 'talents'>>;
