/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type RivalType = (typeof RivalType)[keyof typeof RivalType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RivalType = {
  Minion: "Minion",
  Rival: "Rival",
  Nemesis: "Nemesis",
  Player: "Player",
} as const;
