/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export interface RollTotals {
  success?: number;
  advantage?: number;
  triumph?: number;
  failure?: number;
  threat?: number;
  despair?: number;
}
