/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export interface SelectedChoice {
  name?: string;
  count?: number;
}
