/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Party } from "./party";

export interface Session {
  /** @minLength 1 */
  name: string;
  party?: Party;
  active?: boolean;
  player?: number;
  gm?: number;
  sceneIds?: string[];
}
