/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Skill } from './skill';

export interface SkillRankModifier {
  /** The skill whose rank is modified */
  skill: Skill;
  /** The number of ranks to add; positive values increase the rank */
  ranks: number;
}
