/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { CharacteristicType } from './characteristicType';
import type { SkillType } from './skillType';

/**
 * Setting-specific skills
 */
export interface Skill {
  id: string;
  /** @minLength 1 */
  name: string;
  characteristic: CharacteristicType;
  type: SkillType;
  initiative: boolean;
  /** A short summary of the skill */
  summary: string;
  /** A detailed description of the skill */
  description: string;
}
