/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { SkillCharacteristic } from './skillCharacteristic';
import type { SkillType } from './skillType';

/**
 * Setting-specific skills
 */
export interface Skill {
  id: string;
  /** @minLength 1 */
  name: string;
  /** The type of Characteristic */
  characteristic: SkillCharacteristic;
  type: SkillType;
  initiative: boolean;
}
