/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Difficulty } from './difficulty';
import type { Effect } from './effect';
import type { Skill } from './skill';

export interface Spell {
  id: string;
  name: string;
  concentration: boolean;
  difficulty: Difficulty;
  description: string;
  skills: Skill[];
  effects: Effect[];
}
