/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * A spell effect that can be applied to a spell, each increasing the difficulty
 */
export interface SpellEffect {
  name: string;
  description: string;
  /** Number of difficulty dice added when this effect is applied */
  difficultyIncrease: number;
}
