/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type SpellDifficulty =
  (typeof SpellDifficulty)[keyof typeof SpellDifficulty];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SpellDifficulty = {
  Easy: "Easy",
  Average: "Average",
  Hard: "Hard",
  Daunting: "Daunting",
  Formidable: "Formidable",
} as const;
