/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Difficulty } from "./difficulty";
import type { Skill } from "./skill";
import type { Effect } from "./effect";

export interface Spell {
  id: string;
  name: string;
  concentration: boolean;
  difficulty: Difficulty;
  description: string;
  skills: Skill[];
  effects: Effect[];
}
