/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Difficulty } from './difficulty';
import type { RangeBand } from './rangeBand';
import type { Skill } from './skill';
import type { SpellEffect } from './spellEffect';

/**
 * Setting-specific Spell
 */
export interface Spell {
  id: string;
  name: string;
  concentration: boolean;
  difficulty: Difficulty;
  range: RangeBand;
  skills: Skill[];
  effects: SpellEffect[];
}
