/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type StartEncounter200 = {[key: string]: string};
