/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { StartingGearOption } from './startingGearOption';

/**
 * A single starting gear entry; the player must choose exactly one of the listed options
 */
export interface StartingGearSlot {
  /** The selectable options for this entry; a list of one means the item is fixed with no choice */
  options: StartingGearOption[];
}
