/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Starting currency awarded to a player character of this career
 */
export interface StartingMoney {
  /**
     * Fixed base amount of currency awarded (e.g. 200)
     * @minimum 0
     */
  base: number;
  /** Optional dice expression added on top of the base amount (e.g. "1d100") */
  diceExpression?: string;
  /** Name of the currency (e.g. "silver coins") */
  currency: string;
}
