/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { ItemTemplate } from './itemTemplate';

/**
 * One selectable option within a starting gear entry; may be a single item or a bundle of items
 */
export interface StartingGearOption {
  /** Human-readable label for this option (e.g. "traveling gear") */
  description?: string;
  /** The item or items the player receives when they choose this option */
  items: ItemTemplate[];
}
