/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export interface StatModifiers {
  wounds: number;
  strain: number;
  soak: number;
  defense: number;
}
