/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type StatusEffectType = typeof StatusEffectType[keyof typeof StatusEffectType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StatusEffectType = {
  Disoriented: 'Disoriented',
  Immobilized: 'Immobilized',
  Staggered: 'Staggered',
} as const;
