/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { StatsType } from "./statsType";

export interface Stats {
  /** @minimum 0 */
  current: number;
  /** @minimum 0 */
  threshold: number;
  type: StatsType;
}
