/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { TalentActivation } from './talentActivation';
import type { TalentTier } from './talentTier';
import type { Cost } from './cost';
import type { Limit } from './limit';
import type { TalentSkills } from './talentSkills';
import type { TalentStats } from './talentStats';
import type { TalentSkillCheck } from './talentSkillCheck';
import type { Action } from './action';
import type { TalentRollModifiers } from './talentRollModifiers';
import type { Modifier } from './modifier';

export interface Talent {
  id?: string;
  /** @minLength 1 */
  name: string;
  activation?: TalentActivation;
  tier?: TalentTier;
  ranked: boolean;
  summary?: string;
  description?: string;
  cost?: Cost;
  limit?: Limit;
  talentSkills?: TalentSkills;
  talentStats?: TalentStats;
  talentSkillCheck?: TalentSkillCheck;
  action?: Action;
  talentRollModifiers?: TalentRollModifiers[];
  modifiers?: Modifier[];
}
