/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Action } from './action';
import type { Activation } from './activation';
import type { Cost } from './cost';
import type { Limit } from './limit';
import type { Modifier } from './modifier';
import type { StatModifiers } from './statModifiers';
import type { TalentRollModifiers } from './talentRollModifiers';
import type { TalentSkillCheck } from './talentSkillCheck';
import type { TalentSkills } from './talentSkills';
import type { TalentTier } from './talentTier';

/**
 * Setting-specific talents
 */
export interface Talent {
  id: string;
  /** @minLength 1 */
  name: string;
  activation: Activation;
  tier: TalentTier;
  ranked: boolean;
  summary: string;
  description: string;
  cost: Cost;
  limit: Limit;
  talentSkills: TalentSkills;
  statModifiers: StatModifiers;
  talentSkillCheck: TalentSkillCheck;
  action: Action;
  talentRollModifiers: TalentRollModifiers[];
  modifiers: Modifier[];
}
