/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { PlayerSkill } from './playerSkill';

export interface TalentRollModifiers {
  skill: PlayerSkill;
}
