/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export interface TalentStats {
  wounds?: number;
  strain?: number;
  soak?: number;
  defense?: number;
}
