/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { AbilityModifiers } from './abilityModifiers';
import type { Action } from './action';
import type { Activation } from './activation';
import type { Cost } from './cost';
import type { DiceModifier } from './diceModifier';
import type { Limit } from './limit';
import type { Maneuver } from './maneuver';
import type { StatModifiers } from './statModifiers';
import type { TalentSkillCheck } from './talentSkillCheck';
import type { TalentSkills } from './talentSkills';
import type { Tier } from './tier';

/**
 * Setting-specific talents
 */
export interface Talent {
  id: string;
  /** @minLength 1 */
  name: string;
  activation: Activation;
  tier: Tier;
  ranked: boolean;
  summary: string;
  description: string;
  cost: Cost;
  limit: Limit;
  talentSkills: TalentSkills;
  statModifiers: StatModifiers;
  abilityModifiers: AbilityModifiers;
  talentSkillCheck: TalentSkillCheck;
  diceModifiers: DiceModifier[];
  /** Configuration for talents that function as a maneuver activation */
  maneuver?: Maneuver;
  /** Configuration for talents that function as a action activation */
  action?: Action;
}
