/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Skill } from './skill';

export interface TalentSkills {
  potentialCareerSkills: Skill[];
}
