/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type TalentSkillCheckDifficulty = typeof TalentSkillCheckDifficulty[keyof typeof TalentSkillCheckDifficulty];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TalentSkillCheckDifficulty = {
  Easy: 'Easy',
  Average: 'Average',
  Hard: 'Hard',
  Daunting: 'Daunting',
  Formidable: 'Formidable',
} as const;
