/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type TalentTier = typeof TalentTier[keyof typeof TalentTier];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TalentTier = {
  First: 'First',
  Second: 'Second',
  Third: 'Third',
  Fourth: 'Fourth',
  Fifth: 'Fifth',
} as const;
