/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { AdversarySkill } from './adversarySkill';
import type { Difficulty } from './difficulty';
import type { PlayerSkill } from './playerSkill';

export interface TalentSkillCheck {
  skill: PlayerSkill;
  difficulty: Difficulty;
  opposedSkill: AdversarySkill;
}
