/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Difficulty } from './difficulty';
import type { RankedSkill } from './rankedSkill';
import type { StatusEffect } from './statusEffect';

export interface TalentSkillCheck {
  skill: RankedSkill;
  difficulty: Difficulty;
  opposedSkill: RankedSkill;
  /** Condition inflicted on the opponent when the check succeeds */
  onSuccessCondition?: StatusEffect;
}
