/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { ActorSkill } from "./actorSkill";

export interface TalentRollModifiers {
  skill: ActorSkill;
}
