/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type Target = typeof Target[keyof typeof Target];


export const Target = {
  Self: 'Self',
  Opponent: 'Opponent',
  Engaged_Ally: 'Engaged Ally',
  Engaged_Enemy: 'Engaged Enemy',
  Any_Ally: 'Any Ally',
  Any_Enemy: 'Any Enemy',
} as const;
