/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Derived Threshold
 */
export interface Threshold {
  /**
   * Current value of the Stat
   * @minimum 0
   */
  current: number;
  /**
   * Total value of the Stat
   * @minimum 1
   */
  total: number;
}
