/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type Tier = typeof Tier[keyof typeof Tier];


export const Tier = {
  First: 'First',
  Second: 'Second',
  Third: 'Third',
  Fourth: 'Fourth',
  Fifth: 'Fifth',
} as const;
