/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */

export type UpgradeType = typeof UpgradeType[keyof typeof UpgradeType];


export const UpgradeType = {
  Ability_to_Proficiency: 'Ability to Proficiency',
  Difficulty_to_Challenge: 'Difficulty to Challenge',
} as const;
