/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { CheckContext } from './checkContext';
import type { Duration } from './duration';
import type { Skill } from './skill';
import type { SkillType } from './skillType';
import type { Target } from './target';
import type { UpgradeType } from './upgradeType';

export interface UpgradeModifier {
  /** The direction of the upgrade (ability→proficiency or difficulty→challenge) */
  upgradeType: UpgradeType;
  /** Number of dice to upgrade */
  amount: number;
  /** The kind of check that triggers this modifier */
  checkContext: CheckContext;
  /** Restricts this modifier to checks of a particular skill type; null means any skill type */
  skillType?: SkillType;
  /** Restricts this modifier to a specific skill; null means any skill matching skillType */
  skill?: Skill;
  /** Whether this modifier applies to the character's own rolls or to rolls made against them */
  checkTarget: Target;
  /** How long this upgrade effect lasts; PERMANENT means always active while equipped */
  duration: Duration;
}
