/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Equipment } from './equipment';
import type { EquipmentQuality } from './equipmentQuality';
import type { Modifier } from './modifier';
import type { RangeBand } from './rangeBand';
import type { Skill } from './skill';

export type Weapon = Equipment & {
  id?: string;
  /** @minLength 1 */
  name?: string;
  type?: 'Weapon' | 'Armor' | 'Gear';
  description?: string;
  /** @minimum 0 */
  price?: number;
  restricted?: boolean;
  /** @minimum 0 */
  encumbrance?: number;
  /**
   * @minimum 0
   * @maximum 10
   */
  rarity?: number;
  modifiers?: Modifier[];
  qualities?: EquipmentQuality[];
  /** @minimum 0 */
  damage?: number;
  skill?: Skill;
  /** @minimum 1 */
  critical?: number;
  range?: RangeBand;
  brawn?: boolean;
  /**
   * @minimum 1
   * @maximum 2
   */
  hands?: number;
} & Required<Pick<Equipment & {
  id?: string;
  /** @minLength 1 */
  name?: string;
  type?: 'Weapon' | 'Armor' | 'Gear';
  description?: string;
  /** @minimum 0 */
  price?: number;
  restricted?: boolean;
  /** @minimum 0 */
  encumbrance?: number;
  /**
   * @minimum 0
   * @maximum 10
   */
  rarity?: number;
  modifiers?: Modifier[];
  qualities?: EquipmentQuality[];
  /** @minimum 0 */
  damage?: number;
  skill?: Skill;
  /** @minimum 1 */
  critical?: number;
  range?: RangeBand;
  brawn?: boolean;
  /**
   * @minimum 1
   * @maximum 2
   */
  hands?: number;
}, 'brawn' | 'critical' | 'damage' | 'hands' | 'range' | 'skill'>>;
