/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Skill } from "./skill";
import type { RangeBand } from "./rangeBand";

export type WeaponAllOf = {
  /** @minimum 0 */
  damage?: number;
  skill?: Skill;
  /** @minimum 1 */
  critical?: number;
  range?: RangeBand;
  brawn?: boolean;
  /**
   * @minimum 1
   * @maximum 2
   */
  hands?: number;
};
