/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Skill } from './skill';
import type { RangeBand } from './rangeBand';

export interface WeaponStats {
  /** The skill associated with the weapon */
  skill: Skill;
  /**
   * The damage of the weapon
   * @minimum 0
   */
  damage: number;
  /**
   * The critical rating of the weapon
   * @minimum 1
   */
  critical: number;
  /** The range band of the weapon */
  range: RangeBand;
  /** Whether the weapon damage is increased by Brawn */
  brawn: boolean;
}
