/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Equipment } from './equipment';
import type { WeaponAllOf } from './weaponAllOf';

export type Weapon = Equipment & WeaponAllOf & Required<Pick<Equipment & WeaponAllOf, 'brawn' | 'critical' | 'damage' | 'hands' | 'range' | 'skill'>>;
