/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { RangeBand } from './rangeBand';
import type { Skill } from './skill';

export interface WeaponInstance {
  id: string;
  /** @minLength 1 */
  name: string;
  description: string;
  restricted: boolean;
  /** @minimum 0 */
  encumbrance: number;
  /** @minimum 0 */
  damage: number;
  skill: Skill;
  /** @minimum 1 */
  critical: number;
  range: RangeBand;
  brawn: boolean;
  /**
   * @minimum 1
   * @maximum 2
   */
  hands: number;
}
