/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { ItemTemplate } from './itemTemplate';
import type { RangeBand } from './rangeBand';
import type { Skill } from './skill';

export type WeaponTemplate = ItemTemplate & {
  /** The skill associated with the weapon */
  skill?: Skill;
  /**
   * The damage of the weapon
   * @minimum 0
   */
  damage?: number;
  /**
   * The critical rating of the weapon
   * @minimum 1
   */
  critical?: number;
  /** The range band of the weapon */
  range?: RangeBand;
} & Required<Pick<ItemTemplate & {
  /** The skill associated with the weapon */
  skill?: Skill;
  /**
   * The damage of the weapon
   * @minimum 0
   */
  damage?: number;
  /**
   * The critical rating of the weapon
   * @minimum 1
   */
  critical?: number;
  /** The range band of the weapon */
  range?: RangeBand;
}, 'critical' | 'damage' | 'range' | 'skill'>>;
