/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Genesys API Documentation
 * Interactive API documentation
 * OpenAPI spec version: 1.0
 */
import type { Equipment } from './equipment';
import type { RangeBand } from './rangeBand';
import type { Skill } from './skill';

export type Weapon = Equipment & {
  /** @minimum 0 */
  damage?: number;
  skill?: Skill;
  /** @minimum 1 */
  critical?: number;
  range?: RangeBand;
  brawn?: boolean;
  /**
   * @minimum 1
   * @maximum 2
   */
  hands?: number;
} & Required<Pick<Equipment & {
  /** @minimum 0 */
  damage?: number;
  skill?: Skill;
  /** @minimum 1 */
  critical?: number;
  range?: RangeBand;
  brawn?: boolean;
  /**
   * @minimum 1
   * @maximum 2
   */
  hands?: number;
}, 'brawn' | 'critical' | 'damage' | 'hands' | 'range' | 'skill'>>;
